//! GoldenFixture cluster (0xFC00).
//! @generated by `cargo xtask codegen` — do not edit.

#![allow(
    clippy::all,
    clippy::pedantic,
    dead_code,
    unreachable_pub,
    unused_imports
)]

use crate::datatypes::SemanticTagStruct;
use crate::error::ClusterError;
use crate::types::Nullable;
use matter_codec::{ContainerKind, Element, Tag, TlvReader, TlvWriter, Value};

/// Cluster ID.
pub const CLUSTER_ID: u32 = 0xFC00;
/// Cluster revision.
pub const CLUSTER_REVISION: u16 = 1;

/// Command IDs (requests and responses).
pub mod command_id {
    /// `Reset` (request).
    pub const RESET: u32 = 0x00;
    /// `SetLevel` (request).
    pub const SET_LEVEL: u32 = 0x01;
    /// `SetLevelResponse` (response).
    pub const SET_LEVEL_RESPONSE: u32 = 0x02;
    /// `SetPoint` (request).
    pub const SET_POINT: u32 = 0x03;
    /// `Pick` (request).
    /// Provisional in the Matter specification: a later revision may change or remove it.
    pub const PICK: u32 = 0x04;
}

/// Attribute IDs (cluster-specific).
pub mod attribute_id {
    /// `Switch`.
    pub const SWITCH: u32 = 0x0000;
    /// `Level`.
    pub const LEVEL: u32 = 0x0001;
    /// `Mode`.
    pub const MODE: u32 = 0x0002;
    /// `Flags`.
    pub const FLAGS: u32 = 0x0003;
    /// `Label`.
    pub const LABEL: u32 = 0x0004;
    /// `Token`.
    pub const TOKEN: u32 = 0x0005;
    /// `RawMode`.
    pub const RAW_MODE: u32 = 0x0006;
    /// `Caps`.
    pub const CAPS: u32 = 0x0007;
    /// `Point`.
    pub const POINT: u32 = 0x0008;
    /// `Ids`.
    pub const IDS: u32 = 0x0009;
    /// `Points`.
    pub const POINTS: u32 = 0x000A;
    /// `Scoped`.
    pub const SCOPED: u32 = 0x000B;
    /// `Draft`.
    /// Provisional in the Matter specification: a later revision may change or remove it.
    pub const DRAFT: u32 = 0x000C;
}

/// Event IDs.
pub mod event_id {
    /// `Tripped` (critical priority).
    pub const TRIPPED: u32 = 0x00;
    /// `LevelChanged` (info priority).
    pub const LEVEL_CHANGED: u32 = 0x01;
    /// `Drafted` (info priority).
    /// Provisional in the Matter specification: a later revision may change or remove it.
    pub const DRAFTED: u32 = 0x02;
}

bitflags::bitflags! {
    /// `GoldenFixture` feature bits (FeatureMap).
    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
    pub struct Feature: u32 {
        /// FeatureA (FA).
        const FA = 1 << 0;
        /// FeatureB (FB).
        /// Provisional in the Matter specification: a later revision may change or remove it.
        const FB = 1 << 1;
    }
}

/// `ModeEnum` (enum8).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ModeEnum {
    /// Auto = 0.
    Auto,
    /// Manual = 1.
    Manual,
    /// A value not known to this codegen revision.
    Unknown(u8),
}

impl ModeEnum {
    /// Decode from its raw discriminant (unknown → `Unknown`).
    #[must_use]
    pub fn from_raw(v: u8) -> Self {
        match v {
            0 => Self::Auto,
            1 => Self::Manual,
            other => Self::Unknown(other),
        }
    }
    /// The raw discriminant.
    #[must_use]
    pub fn to_raw(self) -> u8 {
        match self {
            Self::Auto => 0,
            Self::Manual => 1,
            Self::Unknown(v) => v,
        }
    }
}

bitflags::bitflags! {
    /// `FlagsBitmap` (map8).
    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
    pub struct FlagsBitmap: u8 {
        /// Alpha.
        const ALPHA = 1 << 0;
        /// Beta.
        const BETA = 1 << 1;
    }
}

bitflags::bitflags! {
    /// `WideFlags` (map16).
    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
    pub struct WideFlags: u16 {
        /// First.
        const FIRST = 1 << 0;
        /// Ninth.
        const NINTH = 1 << 8;
    }
}

/// `PickStruct` struct.
///
/// Generated from the Matter global type `pickdesc`.
///
/// Choice group `a`: a sender includes at least one of `small`, `large`. Not checked when encoding.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub struct PickStruct {
    /// Field Small (tag 0).
    pub small: Option<u8>,
    /// Field Large (tag 1).
    pub large: Option<u16>,
    /// Field Draft (tag 2).
    /// Provisional in the Matter specification: a later revision may change or remove it.
    pub draft: Option<u8>,
}

/// `PointStruct` struct.
#[derive(Clone, Debug, PartialEq)]
pub struct PointStruct {
    /// Field X (tag 0).
    pub x: u16,
    /// Field Y (tag 1).
    pub y: u16,
}

/// `ScopedEntryStruct` struct.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub struct ScopedEntryStruct {
    /// Field Secret (tag 1).
    /// Fabric-sensitive: `None` when the device withheld it because the entry
    /// belongs to another fabric (unfiltered read).
    pub secret: Option<u16>,
    /// Field Kind (tag 2).
    /// Fabric-sensitive: `None` when the device withheld it because the entry
    /// belongs to another fabric (unfiltered read).
    pub kind: Option<Nullable<ModeEnum>>,
    /// Field Note (tag 3).
    pub note: Option<String>,
    /// Field Alias (tag 4).
    /// Fabric-sensitive: `None` when the device withheld it because the entry
    /// belongs to another fabric (unfiltered read).
    pub alias: Option<String>,
    /// Field FabricIndex (tag 254).
    pub fabric_index: u8,
}

impl PickStruct {
    /// Decode the fields of an already-opened anonymous structure
    /// (reader positioned after the struct start; consumes to its end).
    ///
    /// # Errors
    /// Returns [`ClusterError`] on a malformed structure or missing required field.
    pub fn decode_from(r: &mut TlvReader<'_>) -> Result<Self, ClusterError> {
        let mut f_small: Option<u8> = None;
        let mut f_large: Option<u16> = None;
        let mut f_draft: Option<u8> = None;
        loop {
            match r.next()? {
                Some(Element::ContainerEnd) => break,
                Some(Element::Scalar {
                    tag: Tag::Context(0),
                    value: Value::Uint(v),
                }) => {
                    f_small =
                        Some(u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Small"))?)
                }
                Some(Element::Scalar {
                    tag: Tag::Context(1),
                    value: Value::Uint(v),
                }) => {
                    f_large =
                        Some(u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Large"))?)
                }
                Some(Element::Scalar {
                    tag: Tag::Context(2),
                    value: Value::Uint(v),
                }) => {
                    f_draft =
                        Some(u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Draft"))?)
                }
                None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
                Some(Element::ContainerStart { .. }) => r.skip_container()?,
                Some(_) => {} // unknown/future scalar — skip
            }
        }
        Ok(Self {
            small: f_small,
            large: f_large,
            draft: f_draft,
        })
    }
    /// Decode from a standalone anonymous TLV structure.
    ///
    /// # Errors
    /// Returns [`ClusterError`] if the bytes are not an anonymous structure or a field is malformed.
    pub fn decode(tlv: &[u8]) -> Result<Self, ClusterError> {
        let mut r = TlvReader::new(tlv);
        match r.next()? {
            Some(Element::ContainerStart {
                kind: ContainerKind::Structure,
                ..
            }) => {}
            _ => {
                return Err(ClusterError::UnexpectedType {
                    context: "PickStruct",
                })
            }
        }
        Self::decode_from(&mut r)
    }
    /// Write this struct's fields into an already-open container.
    #[allow(clippy::expect_used)] // Vec-backed TlvWriter is infallible.
    pub fn write_fields(&self, w: &mut TlvWriter<'_>) {
        if let Some(small) = &self.small {
            w.put_uint(Tag::Context(0), u64::from(*small))
                .expect("infallible: vec writer");
        }
        if let Some(large) = &self.large {
            w.put_uint(Tag::Context(1), u64::from(*large))
                .expect("infallible: vec writer");
        }
        if let Some(draft) = &self.draft {
            w.put_uint(Tag::Context(2), u64::from(*draft))
                .expect("infallible: vec writer");
        }
    }
    /// Encode as a standalone anonymous TLV structure.
    #[must_use]
    #[allow(clippy::expect_used)] // Vec-backed TlvWriter is infallible.
    pub fn encode(&self) -> Vec<u8> {
        let mut buf = Vec::new();
        let mut w = TlvWriter::new(&mut buf);
        w.start_structure(Tag::Anonymous)
            .expect("infallible: vec writer");
        self.write_fields(&mut w);
        w.end_container().expect("infallible: vec writer");
        buf
    }
}

impl PointStruct {
    /// Decode the fields of an already-opened anonymous structure
    /// (reader positioned after the struct start; consumes to its end).
    ///
    /// # Errors
    /// Returns [`ClusterError`] on a malformed structure or missing required field.
    pub fn decode_from(r: &mut TlvReader<'_>) -> Result<Self, ClusterError> {
        let mut f_x: Option<u16> = None;
        let mut f_y: Option<u16> = None;
        loop {
            match r.next()? {
                Some(Element::ContainerEnd) => break,
                Some(Element::Scalar {
                    tag: Tag::Context(0),
                    value: Value::Uint(v),
                }) => f_x = Some(u16::try_from(v).map_err(|_| ClusterError::InvalidLength("X"))?),
                Some(Element::Scalar {
                    tag: Tag::Context(1),
                    value: Value::Uint(v),
                }) => f_y = Some(u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Y"))?),
                None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
                Some(Element::ContainerStart { .. }) => r.skip_container()?,
                Some(_) => {} // unknown/future scalar — skip
            }
        }
        Ok(Self {
            x: f_x.ok_or(ClusterError::MissingField("X"))?,
            y: f_y.ok_or(ClusterError::MissingField("Y"))?,
        })
    }
    /// Decode from a standalone anonymous TLV structure.
    ///
    /// # Errors
    /// Returns [`ClusterError`] if the bytes are not an anonymous structure or a field is malformed.
    pub fn decode(tlv: &[u8]) -> Result<Self, ClusterError> {
        let mut r = TlvReader::new(tlv);
        match r.next()? {
            Some(Element::ContainerStart {
                kind: ContainerKind::Structure,
                ..
            }) => {}
            _ => {
                return Err(ClusterError::UnexpectedType {
                    context: "PointStruct",
                })
            }
        }
        Self::decode_from(&mut r)
    }
    /// Write this struct's fields into an already-open container.
    #[allow(clippy::expect_used)] // Vec-backed TlvWriter is infallible.
    pub fn write_fields(&self, w: &mut TlvWriter<'_>) {
        w.put_uint(Tag::Context(0), u64::from(self.x))
            .expect("infallible: vec writer");
        w.put_uint(Tag::Context(1), u64::from(self.y))
            .expect("infallible: vec writer");
    }
    /// Encode as a standalone anonymous TLV structure.
    #[must_use]
    #[allow(clippy::expect_used)] // Vec-backed TlvWriter is infallible.
    pub fn encode(&self) -> Vec<u8> {
        let mut buf = Vec::new();
        let mut w = TlvWriter::new(&mut buf);
        w.start_structure(Tag::Anonymous)
            .expect("infallible: vec writer");
        self.write_fields(&mut w);
        w.end_container().expect("infallible: vec writer");
        buf
    }
}

impl ScopedEntryStruct {
    /// Decode the fields of an already-opened anonymous structure
    /// (reader positioned after the struct start; consumes to its end).
    ///
    /// # Errors
    /// Returns [`ClusterError`] on a malformed structure or missing required field.
    pub fn decode_from(r: &mut TlvReader<'_>) -> Result<Self, ClusterError> {
        let mut f_secret: Option<u16> = None;
        let mut f_kind: Option<Nullable<ModeEnum>> = None;
        let mut f_note: Option<String> = None;
        let mut f_alias: Option<String> = None;
        let mut f_fabric_index: Option<u8> = None;
        loop {
            match r.next()? {
                Some(Element::ContainerEnd) => break,
                Some(Element::Scalar {
                    tag: Tag::Context(1),
                    value: Value::Uint(v),
                }) => {
                    f_secret =
                        Some(u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Secret"))?)
                }
                Some(Element::Scalar {
                    tag: Tag::Context(2),
                    value: Value::Null,
                }) => f_kind = Some(Nullable::Null),
                Some(Element::Scalar {
                    tag: Tag::Context(2),
                    value: Value::Uint(v),
                }) => {
                    f_kind = Some(Nullable::Value(ModeEnum::from_raw(
                        u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Kind"))?,
                    )))
                }
                Some(Element::Scalar {
                    tag: Tag::Context(3),
                    value: Value::Utf8(v),
                }) => f_note = Some(v),
                Some(Element::Scalar {
                    tag: Tag::Context(4),
                    value: Value::Utf8(v),
                }) => f_alias = Some(v),
                Some(Element::Scalar {
                    tag: Tag::Context(254),
                    value: Value::Uint(v),
                }) => {
                    f_fabric_index = Some(
                        u8::try_from(v).map_err(|_| ClusterError::InvalidLength("FabricIndex"))?,
                    )
                }
                None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
                Some(Element::ContainerStart { .. }) => r.skip_container()?,
                Some(_) => {} // unknown/future scalar — skip
            }
        }
        Ok(Self {
            secret: f_secret,
            kind: f_kind,
            note: f_note,
            alias: f_alias,
            fabric_index: f_fabric_index.ok_or(ClusterError::MissingField("FabricIndex"))?,
        })
    }
    /// Decode from a standalone anonymous TLV structure.
    ///
    /// # Errors
    /// Returns [`ClusterError`] if the bytes are not an anonymous structure or a field is malformed.
    pub fn decode(tlv: &[u8]) -> Result<Self, ClusterError> {
        let mut r = TlvReader::new(tlv);
        match r.next()? {
            Some(Element::ContainerStart {
                kind: ContainerKind::Structure,
                ..
            }) => {}
            _ => {
                return Err(ClusterError::UnexpectedType {
                    context: "ScopedEntryStruct",
                })
            }
        }
        Self::decode_from(&mut r)
    }
    /// Write this struct's fields into an already-open container.
    ///
    /// A device withholds this struct's fabric-sensitive fields for entries of
    /// other fabrics, so a read result can hold entries with them `None`. Filter
    /// a read result to your own `fabric_index` before writing it back.
    ///
    /// # Errors
    /// [`ClusterError::MissingField`] if a fabric-sensitive field required on
    /// write is `None`; nothing is written in that case.
    #[allow(clippy::expect_used)] // Vec-backed TlvWriter is infallible.
    pub fn write_fields(&self, w: &mut TlvWriter<'_>) -> Result<(), ClusterError> {
        if self.secret.is_none() {
            return Err(ClusterError::MissingField("Secret"));
        }
        if self.kind.is_none() {
            return Err(ClusterError::MissingField("Kind"));
        }
        if let Some(secret) = &self.secret {
            w.put_uint(Tag::Context(1), u64::from(*secret))
                .expect("infallible: vec writer");
        }
        if let Some(kind) = &self.kind {
            match kind {
                Nullable::Null => w.put_null(Tag::Context(2)).expect("infallible: vec writer"),
                Nullable::Value(kind) => {
                    w.put_uint(Tag::Context(2), u64::from((*kind).to_raw()))
                        .expect("infallible: vec writer");
                }
            }
        }
        if let Some(note) = &self.note {
            w.put_utf8(Tag::Context(3), &*note)
                .expect("infallible: vec writer");
        }
        if let Some(alias) = &self.alias {
            w.put_utf8(Tag::Context(4), &*alias)
                .expect("infallible: vec writer");
        }
        w.put_uint(Tag::Context(254), u64::from(self.fabric_index))
            .expect("infallible: vec writer");
        Ok(())
    }
    /// Encode as a standalone anonymous TLV structure.
    ///
    /// # Errors
    /// [`ClusterError::MissingField`] if a fabric-sensitive field required on
    /// write is `None` (see [`Self::write_fields`]).
    #[allow(clippy::expect_used)] // Vec-backed TlvWriter is infallible.
    pub fn encode(&self) -> Result<Vec<u8>, ClusterError> {
        let mut buf = Vec::new();
        let mut w = TlvWriter::new(&mut buf);
        w.start_structure(Tag::Anonymous)
            .expect("infallible: vec writer");
        self.write_fields(&mut w)?;
        w.end_container().expect("infallible: vec writer");
        Ok(buf)
    }
}

/// Decode the `Switch` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_switch(tlv: &[u8]) -> Result<bool, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Bool(v),
            ..
        }) => Ok(v),
        _ => Err(ClusterError::UnexpectedType { context: "Switch" }),
    }
}

/// Decode the `Level` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_level(tlv: &[u8]) -> Result<Nullable<u16>, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Null, ..
        }) => Ok(Nullable::Null),
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(Nullable::Value(
            u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Level"))?,
        )),
        _ => Err(ClusterError::UnexpectedType { context: "Level" }),
    }
}

/// Encode the `Level` attribute value as a standalone TLV element.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_level(value: Nullable<u16>) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    match value {
        Nullable::Null => w.put_null(Tag::Anonymous).expect("infallible: vec writer"),
        Nullable::Value(value) => {
            w.put_uint(Tag::Anonymous, u64::from(value))
                .expect("infallible: vec writer");
        }
    }
    buf
}

/// Decode the `Mode` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_mode(tlv: &[u8]) -> Result<ModeEnum, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(ModeEnum::from_raw(
            u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Mode"))?,
        )),
        _ => Err(ClusterError::UnexpectedType { context: "Mode" }),
    }
}

/// Encode the `Mode` attribute value as a standalone TLV element.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_mode(value: ModeEnum) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.put_uint(Tag::Anonymous, u64::from(value.to_raw()))
        .expect("infallible: vec writer");
    buf
}

/// Decode the `Flags` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_flags(tlv: &[u8]) -> Result<FlagsBitmap, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(FlagsBitmap::from_bits_retain(
            u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Flags"))?,
        )),
        _ => Err(ClusterError::UnexpectedType { context: "Flags" }),
    }
}

/// Decode the `Label` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_label(tlv: &[u8]) -> Result<String, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Utf8(v),
            ..
        }) => Ok(v),
        _ => Err(ClusterError::UnexpectedType { context: "Label" }),
    }
}

/// Encode the `Label` attribute value as a standalone TLV element.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_label(value: &String) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.put_utf8(Tag::Anonymous, &value)
        .expect("infallible: vec writer");
    buf
}

/// Decode the `Token` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_token(tlv: &[u8]) -> Result<Vec<u8>, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Bytes(v),
            ..
        }) => Ok(v),
        _ => Err(ClusterError::UnexpectedType { context: "Token" }),
    }
}

/// Decode the `RawMode` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_raw_mode(tlv: &[u8]) -> Result<u8, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(u8::try_from(v).map_err(|_| ClusterError::InvalidLength("RawMode"))?),
        _ => Err(ClusterError::UnexpectedType { context: "RawMode" }),
    }
}

/// Encode the `RawMode` attribute value as a standalone TLV element.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_raw_mode(value: u8) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.put_uint(Tag::Anonymous, u64::from(value))
        .expect("infallible: vec writer");
    buf
}

/// Decode the `Caps` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_caps(tlv: &[u8]) -> Result<WideFlags, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(WideFlags::from_bits_retain(
            u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Caps"))?,
        )),
        _ => Err(ClusterError::UnexpectedType { context: "Caps" }),
    }
}

/// Decode the `Point` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_point(tlv: &[u8]) -> Result<PointStruct, ClusterError> {
    PointStruct::decode(tlv)
}

/// Decode the `Ids` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_ids(tlv: &[u8]) -> Result<Vec<u32>, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::ContainerStart {
            kind: ContainerKind::Array,
            ..
        }) => {}
        _ => return Err(ClusterError::UnexpectedType { context: "Ids" }),
    }
    let r = &mut r;
    let mut out = Vec::new();
    loop {
        match r.next()? {
            Some(Element::ContainerEnd) => break,
            Some(Element::Scalar {
                value: Value::Uint(v),
                ..
            }) => out.push(u32::try_from(v).map_err(|_| ClusterError::InvalidLength("Ids"))?),
            None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
            Some(Element::ContainerStart { .. }) => r.skip_container()?,
            Some(_) => {} // skip unknown scalar
        }
    }
    Ok(out)
}

/// Decode the `Points` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_points(tlv: &[u8]) -> Result<Vec<PointStruct>, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::ContainerStart {
            kind: ContainerKind::Array,
            ..
        }) => {}
        _ => return Err(ClusterError::UnexpectedType { context: "Points" }),
    }
    let r = &mut r;
    let mut out = Vec::new();
    loop {
        match r.next()? {
            Some(Element::ContainerEnd) => break,
            Some(Element::ContainerStart {
                kind: ContainerKind::Structure,
                ..
            }) => {
                out.push(PointStruct::decode_from(r)?);
            }
            None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
            Some(Element::ContainerStart { .. }) => r.skip_container()?,
            Some(_) => {} // skip unknown scalar
        }
    }
    Ok(out)
}

/// Decode the `Scoped` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_scoped(tlv: &[u8]) -> Result<Vec<ScopedEntryStruct>, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::ContainerStart {
            kind: ContainerKind::Array,
            ..
        }) => {}
        _ => return Err(ClusterError::UnexpectedType { context: "Scoped" }),
    }
    let r = &mut r;
    let mut out = Vec::new();
    loop {
        match r.next()? {
            Some(Element::ContainerEnd) => break,
            Some(Element::ContainerStart {
                kind: ContainerKind::Structure,
                ..
            }) => {
                out.push(ScopedEntryStruct::decode_from(r)?);
            }
            None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
            Some(Element::ContainerStart { .. }) => r.skip_container()?,
            Some(_) => {} // skip unknown scalar
        }
    }
    Ok(out)
}

/// Decode the `Draft` attribute value.
///
/// Provisional in the Matter specification: a later revision may change or remove it.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_draft(tlv: &[u8]) -> Result<u8, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Draft"))?),
        _ => Err(ClusterError::UnexpectedType { context: "Draft" }),
    }
}

/// Encode the `Draft` attribute value as a standalone TLV element.
///
/// Provisional in the Matter specification: a later revision may change or remove it.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_draft(value: u8) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.put_uint(Tag::Anonymous, u64::from(value))
        .expect("infallible: vec writer");
    buf
}

/// Encode the `Reset` command request payload.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_reset() -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.start_structure(Tag::Anonymous)
        .expect("infallible: vec writer");
    w.end_container().expect("infallible: vec writer");
    buf
}

/// Encode the `SetLevel` command request payload.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_set_level(target: u16, mode: Option<ModeEnum>) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.start_structure(Tag::Anonymous)
        .expect("infallible: vec writer");
    w.put_uint(Tag::Context(0), u64::from(target))
        .expect("infallible: vec writer");
    if let Some(mode) = mode {
        w.put_uint(Tag::Context(1), u64::from(mode.to_raw()))
            .expect("infallible: vec writer");
    }
    w.end_container().expect("infallible: vec writer");
    buf
}

/// Decoded `SetLevelResponse` payload.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub struct SetLevelResponse {
    /// Field Status (tag 0).
    pub status: u8,
    /// Field Reached (tag 1).
    pub reached: Option<u16>,
}

impl SetLevelResponse {
    /// Decode the fields of an already-opened anonymous structure
    /// (reader positioned after the struct start; consumes to its end).
    ///
    /// # Errors
    /// Returns [`ClusterError`] on a malformed structure or missing required field.
    pub fn decode_from(r: &mut TlvReader<'_>) -> Result<Self, ClusterError> {
        let mut f_status: Option<u8> = None;
        let mut f_reached: Option<u16> = None;
        loop {
            match r.next()? {
                Some(Element::ContainerEnd) => break,
                Some(Element::Scalar {
                    tag: Tag::Context(0),
                    value: Value::Uint(v),
                }) => {
                    f_status =
                        Some(u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Status"))?)
                }
                Some(Element::Scalar {
                    tag: Tag::Context(1),
                    value: Value::Uint(v),
                }) => {
                    f_reached =
                        Some(u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Reached"))?)
                }
                None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
                Some(Element::ContainerStart { .. }) => r.skip_container()?,
                Some(_) => {} // unknown/future scalar — skip
            }
        }
        Ok(Self {
            status: f_status.ok_or(ClusterError::MissingField("Status"))?,
            reached: f_reached,
        })
    }
    /// Decode from a standalone anonymous TLV structure.
    ///
    /// # Errors
    /// Returns [`ClusterError`] if the bytes are not an anonymous structure or a field is malformed.
    pub fn decode(tlv: &[u8]) -> Result<Self, ClusterError> {
        let mut r = TlvReader::new(tlv);
        match r.next()? {
            Some(Element::ContainerStart {
                kind: ContainerKind::Structure,
                ..
            }) => {}
            _ => {
                return Err(ClusterError::UnexpectedType {
                    context: "SetLevelResponse",
                })
            }
        }
        Self::decode_from(&mut r)
    }
}

/// Encode the `SetPoint` command request payload.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_set_point(point: PointStruct) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.start_structure(Tag::Anonymous)
        .expect("infallible: vec writer");
    w.start_structure(Tag::Context(0))
        .expect("infallible: vec writer");
    point.write_fields(&mut w);
    w.end_container().expect("infallible: vec writer");
    w.end_container().expect("infallible: vec writer");
    buf
}

/// Encode the `Pick` command request payload.
///
/// Provisional in the Matter specification: a later revision may change or remove it.
///
/// Choice group `a`: a sender includes exactly one of `small`, `large`. Not checked when encoding.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_pick(small: Option<u8>, large: Option<u16>) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.start_structure(Tag::Anonymous)
        .expect("infallible: vec writer");
    if let Some(small) = small {
        w.put_uint(Tag::Context(0), u64::from(small))
            .expect("infallible: vec writer");
    }
    if let Some(large) = large {
        w.put_uint(Tag::Context(1), u64::from(large))
            .expect("infallible: vec writer");
    }
    w.end_container().expect("infallible: vec writer");
    buf
}

/// Decoded `LevelChangedEvent` payload.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub struct LevelChangedEvent {
    /// Field Previous (tag 0).
    pub previous: u16,
    /// Field Count (tag 1).
    pub count: Option<u8>,
}

impl LevelChangedEvent {
    /// Decode the fields of an already-opened anonymous structure
    /// (reader positioned after the struct start; consumes to its end).
    ///
    /// # Errors
    /// Returns [`ClusterError`] on a malformed structure or missing required field.
    pub fn decode_from(r: &mut TlvReader<'_>) -> Result<Self, ClusterError> {
        let mut f_previous: Option<u16> = None;
        let mut f_count: Option<u8> = None;
        loop {
            match r.next()? {
                Some(Element::ContainerEnd) => break,
                Some(Element::Scalar {
                    tag: Tag::Context(0),
                    value: Value::Uint(v),
                }) => {
                    f_previous = Some(
                        u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Previous"))?,
                    )
                }
                Some(Element::Scalar {
                    tag: Tag::Context(1),
                    value: Value::Uint(v),
                }) => {
                    f_count =
                        Some(u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Count"))?)
                }
                None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
                Some(Element::ContainerStart { .. }) => r.skip_container()?,
                Some(_) => {} // unknown/future scalar — skip
            }
        }
        Ok(Self {
            previous: f_previous.ok_or(ClusterError::MissingField("Previous"))?,
            count: f_count,
        })
    }
    /// Decode from a standalone anonymous TLV structure.
    ///
    /// # Errors
    /// Returns [`ClusterError`] if the bytes are not an anonymous structure or a field is malformed.
    pub fn decode(tlv: &[u8]) -> Result<Self, ClusterError> {
        let mut r = TlvReader::new(tlv);
        match r.next()? {
            Some(Element::ContainerStart {
                kind: ContainerKind::Structure,
                ..
            }) => {}
            _ => {
                return Err(ClusterError::UnexpectedType {
                    context: "LevelChangedEvent",
                })
            }
        }
        Self::decode_from(&mut r)
    }
}

/// Decoded `DraftedEvent` payload.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub struct DraftedEvent {
    /// Field Value (tag 0).
    /// Provisional in the Matter specification: a later revision may change or remove it.
    pub value: u8,
}

impl DraftedEvent {
    /// Decode the fields of an already-opened anonymous structure
    /// (reader positioned after the struct start; consumes to its end).
    ///
    /// # Errors
    /// Returns [`ClusterError`] on a malformed structure or missing required field.
    pub fn decode_from(r: &mut TlvReader<'_>) -> Result<Self, ClusterError> {
        let mut f_value: Option<u8> = None;
        loop {
            match r.next()? {
                Some(Element::ContainerEnd) => break,
                Some(Element::Scalar {
                    tag: Tag::Context(0),
                    value: Value::Uint(v),
                }) => {
                    f_value =
                        Some(u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Value"))?)
                }
                None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
                Some(Element::ContainerStart { .. }) => r.skip_container()?,
                Some(_) => {} // unknown/future scalar — skip
            }
        }
        Ok(Self {
            value: f_value.ok_or(ClusterError::MissingField("Value"))?,
        })
    }
    /// Decode from a standalone anonymous TLV structure.
    ///
    /// # Errors
    /// Returns [`ClusterError`] if the bytes are not an anonymous structure or a field is malformed.
    pub fn decode(tlv: &[u8]) -> Result<Self, ClusterError> {
        let mut r = TlvReader::new(tlv);
        match r.next()? {
            Some(Element::ContainerStart {
                kind: ContainerKind::Structure,
                ..
            }) => {}
            _ => {
                return Err(ClusterError::UnexpectedType {
                    context: "DraftedEvent",
                })
            }
        }
        Self::decode_from(&mut r)
    }
}
