//! GoldenFixture cluster (0xFC00).
//! @generated by `cargo xtask codegen` — do not edit.

#![allow(clippy::all, clippy::pedantic, dead_code, unreachable_pub)]

use crate::error::ClusterError;
use crate::types::Nullable;
use matter_codec::{ContainerKind, Element, Tag, TlvReader, TlvWriter, Value};

/// Cluster ID.
pub const CLUSTER_ID: u32 = 0xFC00;
/// Cluster revision.
pub const CLUSTER_REVISION: u16 = 1;

/// Command IDs (requests and responses).
pub mod command_id {
    /// `Reset` (request).
    pub const RESET: u32 = 0x00;
    /// `SetLevel` (request).
    pub const SET_LEVEL: u32 = 0x01;
    /// `SetLevelResponse` (response).
    pub const SET_LEVEL_RESPONSE: u32 = 0x02;
}

/// Attribute IDs (cluster-specific).
pub mod attribute_id {
    /// `Switch`.
    pub const SWITCH: u32 = 0x0000;
    /// `Level`.
    pub const LEVEL: u32 = 0x0001;
    /// `Mode`.
    pub const MODE: u32 = 0x0002;
    /// `Flags`.
    pub const FLAGS: u32 = 0x0003;
    /// `Label`.
    pub const LABEL: u32 = 0x0004;
    /// `Token`.
    pub const TOKEN: u32 = 0x0005;
    /// `RawMode`.
    pub const RAW_MODE: u32 = 0x0006;
    /// `Caps`.
    pub const CAPS: u32 = 0x0007;
}

bitflags::bitflags! {
    /// `GoldenFixture` feature bits (FeatureMap).
    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
    pub struct Feature: u32 {
        /// FeatureA (FA).
        const FA = 1 << 0;
        /// FeatureB (FB).
        const FB = 1 << 1;
    }
}

/// `ModeEnum` (enum8).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ModeEnum {
    /// Auto = 0.
    Auto,
    /// Manual = 1.
    Manual,
    /// A value not known to this codegen revision.
    Unknown(u8),
}

impl ModeEnum {
    /// Decode from its raw discriminant (unknown → `Unknown`).
    #[must_use]
    pub fn from_raw(v: u8) -> Self {
        match v {
            0 => Self::Auto,
            1 => Self::Manual,
            other => Self::Unknown(other),
        }
    }
    /// The raw discriminant.
    #[must_use]
    pub fn to_raw(self) -> u8 {
        match self {
            Self::Auto => 0,
            Self::Manual => 1,
            Self::Unknown(v) => v,
        }
    }
}

bitflags::bitflags! {
    /// `FlagsBitmap` (map8).
    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
    pub struct FlagsBitmap: u8 {
        /// Alpha.
        const ALPHA = 1 << 0;
        /// Beta.
        const BETA = 1 << 1;
    }
}

bitflags::bitflags! {
    /// `WideFlags` (map16).
    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
    pub struct WideFlags: u16 {
        /// First.
        const FIRST = 1 << 0;
        /// Ninth.
        const NINTH = 1 << 8;
    }
}

/// Decode the `Switch` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_switch(tlv: &[u8]) -> Result<bool, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Bool(v),
            ..
        }) => Ok(v),
        _ => Err(ClusterError::UnexpectedType { context: "Switch" }),
    }
}

/// Decode the `Level` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_level(tlv: &[u8]) -> Result<Nullable<u16>, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Null, ..
        }) => Ok(Nullable::Null),
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(Nullable::Value(
            u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Level"))?,
        )),
        _ => Err(ClusterError::UnexpectedType { context: "Level" }),
    }
}

/// Encode the `Level` attribute value as a standalone TLV element.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_level(value: Nullable<u16>) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    match value {
        Nullable::Null => w.put_null(Tag::Anonymous).expect("infallible: vec writer"),
        Nullable::Value(value) => {
            w.put_uint(Tag::Anonymous, u64::from(value))
                .expect("infallible: vec writer");
        }
    }
    buf
}

/// Decode the `Mode` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_mode(tlv: &[u8]) -> Result<ModeEnum, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(ModeEnum::from_raw(
            u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Mode"))?,
        )),
        _ => Err(ClusterError::UnexpectedType { context: "Mode" }),
    }
}

/// Encode the `Mode` attribute value as a standalone TLV element.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_mode(value: ModeEnum) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.put_uint(Tag::Anonymous, u64::from(value.to_raw()))
        .expect("infallible: vec writer");
    buf
}

/// Decode the `Flags` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_flags(tlv: &[u8]) -> Result<FlagsBitmap, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(FlagsBitmap::from_bits_truncate(
            u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Flags"))?,
        )),
        _ => Err(ClusterError::UnexpectedType { context: "Flags" }),
    }
}

/// Decode the `Label` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_label(tlv: &[u8]) -> Result<String, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Utf8(v),
            ..
        }) => Ok(v),
        _ => Err(ClusterError::UnexpectedType { context: "Label" }),
    }
}

/// Encode the `Label` attribute value as a standalone TLV element.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_label(value: &String) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.put_utf8(Tag::Anonymous, &value)
        .expect("infallible: vec writer");
    buf
}

/// Decode the `Token` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_token(tlv: &[u8]) -> Result<Vec<u8>, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Bytes(v),
            ..
        }) => Ok(v),
        _ => Err(ClusterError::UnexpectedType { context: "Token" }),
    }
}

/// Decode the `RawMode` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_raw_mode(tlv: &[u8]) -> Result<u8, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(u8::try_from(v).map_err(|_| ClusterError::InvalidLength("RawMode"))?),
        _ => Err(ClusterError::UnexpectedType { context: "RawMode" }),
    }
}

/// Encode the `RawMode` attribute value as a standalone TLV element.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_raw_mode(value: u8) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.put_uint(Tag::Anonymous, u64::from(value))
        .expect("infallible: vec writer");
    buf
}

/// Decode the `Caps` attribute value.
///
/// # Errors
/// Returns [`ClusterError`] on a type mismatch or out-of-range value.
pub fn decode_caps(tlv: &[u8]) -> Result<WideFlags, ClusterError> {
    let mut r = TlvReader::new(tlv);
    match r.next()? {
        Some(Element::Scalar {
            value: Value::Uint(v),
            ..
        }) => Ok(WideFlags::from_bits_truncate(
            u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Caps"))?,
        )),
        _ => Err(ClusterError::UnexpectedType { context: "Caps" }),
    }
}

/// Encode the `Reset` command request payload.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_reset() -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.start_structure(Tag::Anonymous)
        .expect("infallible: vec writer");
    w.end_container().expect("infallible: vec writer");
    buf
}

/// Encode the `SetLevel` command request payload.
#[must_use]
#[allow(clippy::expect_used, clippy::missing_panics_doc)] // Vec-backed TlvWriter is infallible.
pub fn encode_set_level(target: u16, mode: Option<ModeEnum>) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut w = TlvWriter::new(&mut buf);
    w.start_structure(Tag::Anonymous)
        .expect("infallible: vec writer");
    w.put_uint(Tag::Context(0), u64::from(target))
        .expect("infallible: vec writer");
    if let Some(mode) = mode {
        w.put_uint(Tag::Context(1), u64::from(mode.to_raw()))
            .expect("infallible: vec writer");
    }
    w.end_container().expect("infallible: vec writer");
    buf
}

/// Decoded `SetLevelResponse` payload.
#[derive(Clone, Debug, PartialEq)]
pub struct SetLevelResponse {
    /// Field Status (tag 0).
    pub status: u8,
    /// Field Reached (tag 1).
    pub reached: Option<u16>,
}

impl SetLevelResponse {
    /// Decode from an anonymous TLV structure.
    ///
    /// # Errors
    /// Returns [`ClusterError`] on a malformed structure or missing required field.
    pub fn decode(tlv: &[u8]) -> Result<Self, ClusterError> {
        let mut r = TlvReader::new(tlv);
        match r.next()? {
            Some(Element::ContainerStart {
                kind: ContainerKind::Structure,
                ..
            }) => {}
            _ => {
                return Err(ClusterError::UnexpectedType {
                    context: "SetLevelResponse",
                })
            }
        }
        let mut f_status: Option<u8> = None;
        let mut f_reached: Option<u16> = None;
        loop {
            match r.next()? {
                Some(Element::ContainerEnd) => break,
                Some(Element::Scalar {
                    tag: Tag::Context(0),
                    value: Value::Uint(v),
                }) => {
                    f_status =
                        Some(u8::try_from(v).map_err(|_| ClusterError::InvalidLength("Status"))?)
                }
                Some(Element::Scalar {
                    tag: Tag::Context(1),
                    value: Value::Uint(v),
                }) => {
                    f_reached =
                        Some(u16::try_from(v).map_err(|_| ClusterError::InvalidLength("Reached"))?)
                }
                None => return Err(ClusterError::Tlv(matter_codec::Error::UnclosedContainer)),
                Some(_) => {} // unknown/future element — skip
            }
        }
        Ok(Self {
            status: f_status.ok_or(ClusterError::MissingField("Status"))?,
            reached: f_reached,
        })
    }
}
