//! Node Operational Certificate (NOC) issuance.
//!
//! Milestone 6.3 of the `matter-rust` roadmap. The commissioner side of
//! Matter Core Spec §6.4 and §11.18: turn a verified device CSR
//! response into a signed NOC, then encode the OperationalCredentials
//! cluster command payloads (CSRRequest, CSRResponse, AddTrustedRoot,
//! AddNOC, UpdateNOC, NOCResponse) that move the NOC onto the device.
//!
//! # Phase status
//!
//! - **M6.3.1 (current):** [`FabricRecord`] (RCAC keypair + self-signed
//!   root certificate, optional ICAC slots reserved), [`NocError`],
//!   [`NocRng`] / [`SystemNocRng`]. Validates: RCAC self-signs and
//!   re-verifies; `verify_attestation_response` from M6.2 still passes
//!   every existing test bit-identical after the
//!   `verify_dac_signed_elements` extraction.
//! - **M6.3.2 (next):** [`csr`] — NOCSR TLV parsing, PKCS#10
//!   embedded-CSR parsing + self-signature verification, full
//!   `verify_csr_response` (the three-check atomic gate); [`issuer`] —
//!   NOC construction + signing via `fabric.root_signer`.
//! - **M6.3.3:** [`commands`] — OpCreds cluster (`0x003E`) NOC-issuance
//!   subset codecs + matter.js byte-parity gate + fuzz target.
//!
//! # What's deferred past M6.3
//!
//! - **ICAC issuance.** [`FabricRecord::icac_signer`] /
//!   [`FabricRecord::icac_cert`] slots exist; only `new_root_only` is
//!   implemented. Real production controllers need ICAC for
//!   operational-key rotation. Add `FabricRecord::new_with_icac(...)`
//!   + ICAC issuance code path before v1.0 — tracked in `TODO-1.0.md`.
//! - **`ArmFailSafe` / `CommissioningComplete` / `UpdateFabricLabel`** —
//!   GeneralCommissioning cluster, M6.4.
//! - **`NetworkCommissioning` cluster commands** — M6.5.
//! - **`FabricRecord` persistence** — M8.
//! - **End-to-end real-device commissioning** — M6.6.
//!
//! # Trust scope
//!
//! `FabricRecord` is in-memory only. Production callers (M8) own the
//! persistence story. The IPK generated by `new_root_only` is mixed
//! into the AddNOC payload (spec §11.18.5.13) and into operational
//! group-key derivation; treat it as fabric-scoped secret material.

#![forbid(unsafe_code)]

pub mod csr;
pub mod error;
pub mod fabric;
pub mod issuer;

pub use csr::{
    parse_and_verify_csr, parse_nocsr, verify_csr_response, NocsrElements, ParsedCsr, VerifiedCsr,
};
pub use error::{NocError, NocRng, SystemNocRng};
pub use fabric::FabricRecord;
pub use issuer::issue_noc;
