//! Certification Declaration verifier implementation.
//!
//! The verifier performs five checks in order:
//!
//! 1. CMS `SignedData` DER parse via the `cms` crate.
//! 2. Structural validation: a single `SignerInfo`, attached
//!    encapsulated content.
//! 3. ECDSA-P256 / SHA-256 signature verification against each
//!    trusted root's public key; accept on first match.
//! 4. Decode the inner CD TLV via `parse_inner_cd_tlv` (M6.4.3 T30
//!    fills the helper).
//! 5. Cross-check declared VID + PID against the expected pair
//!    supplied by the caller (typically sourced from the verified DAC
//!    subject).
//!
//! The trust store ([`CdSigningRoots`]) holds SEC1-uncompressed P-256
//! public keys for each trusted CSA signing root. Production callers
//! build the store via [`CdSigningRoots::from_pem`]; tests and
//! examples use the bundled CSA-test root via
//! [`CdSigningRoots::with_csa_test_roots`].

#![forbid(unsafe_code)]

use crate::attestation::{AttestationError, ProductId, VendorId};

/// Bundled PEM-encoded `SubjectPublicKeyInfo` for the synthetic
/// CSA-test CD signing root generated by `xtask capture-cd`. The
/// matching private key lives in `test-vectors/commissioning/cd/` and
/// signs the fixture CDs the verifier tests consume.
const CSA_TEST_CD_SIGNING_ROOT_PEM: &[u8] =
    include_bytes!("./csa_cd_signing_roots/csa-test-cd-signing-root.pem");

/// Trusted CSA Certification Declaration signing roots.
///
/// Built from production roots via [`Self::from_pem`] or seeded with
/// the bundled synthetic CSA-test root via
/// [`Self::with_csa_test_roots`].
///
/// Internally stores each trusted root as a SEC1-uncompressed P-256
/// public key (65 bytes: `0x04 || X || Y`) so signature verification
/// can call `ring::signature::UnparsedPublicKey` directly without
/// re-parsing.
#[derive(Debug, Clone)]
pub struct CdSigningRoots {
    /// SEC1-uncompressed P-256 public keys (65 bytes each) for each
    /// trusted root.
    public_keys: Vec<Vec<u8>>,
}

impl CdSigningRoots {
    /// Build a trust store seeded with the bundled synthetic CSA-test
    /// CD signing root.
    ///
    /// **Tests and examples only — do not use in production.** Real
    /// commissioners supply CSA-published roots via
    /// [`Self::from_pem`].
    ///
    /// While M6.4.3 T28 is the active milestone, `parse_pem_public_key`
    /// is a placeholder that always errors, so this constructor
    /// returns an empty trust store. M6.4.3 T29 replaces the
    /// placeholder with a real PEM `SubjectPublicKeyInfo` parser, at
    /// which point the store will load exactly one bundled root.
    #[must_use]
    pub fn with_csa_test_roots() -> Self {
        let pk = parse_pem_public_key(CSA_TEST_CD_SIGNING_ROOT_PEM).ok();
        Self {
            public_keys: pk.into_iter().collect(),
        }
    }

    /// Build a trust store from PEM-encoded P-256
    /// `SubjectPublicKeyInfo` blobs (one per trusted CSA signing
    /// root).
    ///
    /// # Errors
    ///
    /// Returns [`AttestationError::CertificationDeclarationMalformed`]
    /// if any input fails to parse. While M6.4.3 T29 is unimplemented,
    /// every non-empty input fails. An empty slice returns an empty
    /// trust store.
    pub fn from_pem(pems: &[&[u8]]) -> Result<Self, AttestationError> {
        let mut public_keys = Vec::with_capacity(pems.len());
        for raw in pems {
            let pk = parse_pem_public_key(raw)?;
            public_keys.push(pk);
        }
        Ok(Self { public_keys })
    }

    /// Number of trusted roots in the store.
    #[must_use]
    pub fn len(&self) -> usize {
        self.public_keys.len()
    }

    /// Returns `true` if no trusted roots have been loaded.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.public_keys.is_empty()
    }

    /// Internal accessor — borrow the raw 65-byte SEC1 uncompressed
    /// public-key bytes for each trusted root, for the verifier's
    /// signature-check loop.
    fn keys(&self) -> &[Vec<u8>] {
        &self.public_keys
    }
}

/// Verify a Certification Declaration extracted from
/// `attestation_elements` (Matter Core Spec §6.3.1) against a trust
/// store and an expected VID / PID pair.
///
/// Performs five checks in order:
///
/// 1. CMS `SignedData` DER parse via the `cms` crate.
/// 2. Structural validation: a single `SignerInfo`, attached
///    encapsulated content.
/// 3. ECDSA-P256 / SHA-256 signature verification against each
///    trusted root in `trust`; accept on first match.
/// 4. Decode the inner CD TLV.
/// 5. Cross-check declared VID + PID against `expected_vid` /
///    `expected_pid` (sourced from the verified DAC chain by the
///    caller).
///
/// # Errors
///
/// - [`AttestationError::CertificationDeclarationMalformed`] — the
///   CMS DER failed to parse or did not match the expected shape.
/// - [`AttestationError::CertificationDeclarationSignatureInvalid`] —
///   no trusted root accepts the signature.
/// - [`AttestationError::CertificationDeclarationTlvMalformed`] —
///   inner CD TLV missing required fields or malformed.
/// - [`AttestationError::CertificationDeclarationVidMismatch`] —
///   declared VID does not equal `expected_vid`.
/// - [`AttestationError::CertificationDeclarationPidMismatch`] —
///   declared PID list does not contain `expected_pid`.
#[allow(
    clippy::similar_names,
    reason = "the `expected_vid`/`expected_pid` pair mirrors the public-API \
     vocabulary used elsewhere in this crate (VendorId/ProductId); \
     renaming would obscure intent at the call site."
)]
pub fn verify_certification_declaration(
    cd_bytes: &[u8],
    expected_vid: VendorId,
    expected_pid: ProductId,
    trust: &CdSigningRoots,
) -> Result<(), AttestationError> {
    use cms::content_info::ContentInfo;
    use cms::signed_data::SignedData;
    use der::asn1::OctetString;
    use der::{Decode, DecodeValue, Encode, Header, SliceReader, Tag as DerTag};

    // 1. Parse the outer ContentInfo.
    let content_info = ContentInfo::from_der(cd_bytes)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    // ContentInfo.content is an Any wrapping SignedData; re-encode and
    // decode to convert.
    let signed_data_der = content_info
        .content
        .to_der()
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    let signed_data = SignedData::from_der(&signed_data_der)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;

    // 2. Validate shape: exactly one SignerInfo and attached content.
    if signed_data.signer_infos.0.len() != 1 {
        return Err(AttestationError::CertificationDeclarationMalformed);
    }
    let signer = signed_data
        .signer_infos
        .0
        .iter()
        .next()
        .ok_or(AttestationError::CertificationDeclarationMalformed)?;

    // 3. Extract the signed content (the inner CD TLV bytes).
    //
    // `EncapsulatedContentInfo.econtent` is typed `Option<Any>` where
    // the Any wraps an OCTET STRING. We decode the OCTET STRING from
    // the Any's body and copy its bytes — this is the eContent value
    // (the inner CD TLV) the signer signed.
    let econtent = signed_data
        .encap_content_info
        .econtent
        .as_ref()
        .ok_or(AttestationError::CertificationDeclarationMalformed)?;
    // `Any` does not expose its raw value bytes directly; re-encode it
    // then peel off the OCTET STRING tag+length to read the inner
    // bytes via `OctetString::decode_value`.
    let econtent_der = econtent
        .to_der()
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    let mut reader = SliceReader::new(&econtent_der)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    let header = Header::decode(&mut reader)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    if header.tag != DerTag::OctetString {
        return Err(AttestationError::CertificationDeclarationMalformed);
    }
    let octet_string = OctetString::decode_value(&mut reader, header)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    let content_bytes = octet_string.as_bytes().to_vec();

    // 4. Extract the signature bytes.
    let sig = signer.signature.as_bytes();

    // 5. Verify ECDSA-P256 / SHA-256 against each trusted root.
    let mut accepted = false;
    for key in trust.keys() {
        if verify_ecdsa_p256_sha256_fixed(key, &content_bytes, sig).is_ok() {
            accepted = true;
            break;
        }
    }
    if !accepted {
        return Err(AttestationError::CertificationDeclarationSignatureInvalid);
    }

    // 6. Decode the inner CD TLV and cross-check VID / PID.
    let parsed = parse_inner_cd_tlv(&content_bytes)?;
    if parsed.vendor_id != expected_vid {
        return Err(AttestationError::CertificationDeclarationVidMismatch {
            declared: parsed.vendor_id,
            expected: expected_vid,
        });
    }
    if !parsed.product_ids.contains(&expected_pid) {
        return Err(AttestationError::CertificationDeclarationPidMismatch(
            expected_pid,
        ));
    }

    Ok(())
}

/// Decoded view of the inner Certification Declaration TLV — the
/// subset the verifier cross-checks today. T30 fleshes out the parser.
struct ParsedCd {
    /// Vendor ID (Matter Core Spec §6.3.1 tag 1).
    vendor_id: VendorId,
    /// Product ID list (tag 2 — at least one element required).
    product_ids: Vec<ProductId>,
}

/// **Placeholder — M6.4.3 T30 fills this in.**
///
/// Decode the inner CD TLV per Matter Core Spec §6.3.1: an anonymous
/// outer structure with context-tagged fields including tag 1
/// (`vendor_id`, u16) and tag 2 (`product_id_array`, array of u16).
fn parse_inner_cd_tlv(_tlv: &[u8]) -> Result<ParsedCd, AttestationError> {
    Err(AttestationError::CertificationDeclarationTlvMalformed)
}

/// **Placeholder — M6.4.3 T29 fills this in.**
///
/// Parse a PEM-encoded `SubjectPublicKeyInfo` for a P-256 public key
/// and return the SEC1 uncompressed point (65 bytes:
/// `0x04 || X || Y`) suitable for `ring`'s
/// `UnparsedPublicKey<ECDSA_P256_SHA256_FIXED>`.
fn parse_pem_public_key(_pem: &[u8]) -> Result<Vec<u8>, AttestationError> {
    Err(AttestationError::CertificationDeclarationMalformed)
}

/// Verify an ECDSA-P256 / SHA-256 signature in fixed (raw r||s, 64
/// bytes) form against a SEC1-uncompressed P-256 public key.
///
/// Maps any verification failure to
/// [`AttestationError::CertificationDeclarationSignatureInvalid`] —
/// the caller (the per-root loop in
/// [`verify_certification_declaration`]) only cares whether *some*
/// trusted root accepted the signature, not which one rejected it.
fn verify_ecdsa_p256_sha256_fixed(
    public_key: &[u8],
    msg: &[u8],
    sig: &[u8],
) -> Result<(), AttestationError> {
    use ring::signature::{UnparsedPublicKey, ECDSA_P256_SHA256_FIXED};
    let pk = UnparsedPublicKey::new(&ECDSA_P256_SHA256_FIXED, public_key);
    pk.verify(msg, sig)
        .map_err(|_| AttestationError::CertificationDeclarationSignatureInvalid)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn with_csa_test_roots_constructs_at_t28_with_empty_store() {
        // M6.4.3 T29 replaces parse_pem_public_key with a real PEM
        // parser, at which point this assertion tightens to
        // `assert_eq!(trust.len(), 1)`. For T28's placeholder shape,
        // the constructor must not panic and must return a trust store
        // (possibly empty).
        let trust = CdSigningRoots::with_csa_test_roots();
        assert!(
            trust.len() <= 1,
            "T28 placeholder yields 0 roots; T29 yields exactly 1"
        );
    }

    #[test]
    #[allow(clippy::unwrap_used)] // Test-code carve-out: see CLAUDE.md.
    fn from_pem_empty_input_yields_empty_trust_store() {
        let trust = CdSigningRoots::from_pem(&[]).unwrap();
        assert!(trust.is_empty());
        assert_eq!(trust.len(), 0);
    }
}
