//! Certification Declaration verifier implementation.
//!
//! The verifier performs five checks in order:
//!
//! 1. CMS `SignedData` DER parse via the `cms` crate.
//! 2. Structural validation: a single `SignerInfo`, attached
//!    encapsulated content.
//! 3. ECDSA-P256 / SHA-256 signature verification against each
//!    trusted root's public key; accept on first match.
//! 4. Decode the inner CD TLV via `parse_inner_cd_tlv` (M6.4.3 T30
//!    fills the helper).
//! 5. Cross-check declared VID + PID against the expected pair
//!    supplied by the caller (typically sourced from the verified DAC
//!    subject).
//!
//! The trust store ([`CdSigningRoots`]) holds SEC1-uncompressed P-256
//! public keys for each trusted CSA signing root. Production callers
//! build the store via [`CdSigningRoots::from_pem`]; tests and
//! examples use the bundled CSA-test root via
//! [`CdSigningRoots::with_csa_test_roots`].

#![forbid(unsafe_code)]

use crate::attestation::{AttestationError, ProductId, VendorId};

/// Bundled PEM-encoded `SubjectPublicKeyInfo` for the synthetic
/// CSA-test CD signing root generated by `xtask capture-cd`. The
/// matching private key lives in `test-vectors/commissioning/cd/` and
/// signs the fixture CDs the verifier tests consume.
const CSA_TEST_CD_SIGNING_ROOT_PEM: &[u8] =
    include_bytes!("./csa_cd_signing_roots/csa-test-cd-signing-root.pem");

/// Trusted CSA Certification Declaration signing roots.
///
/// Built from production roots via [`Self::from_pem`] or seeded with
/// the bundled synthetic CSA-test root via
/// [`Self::with_csa_test_roots`].
///
/// Internally stores each trusted root as a SEC1-uncompressed P-256
/// public key (65 bytes: `0x04 || X || Y`) so signature verification
/// can call `ring::signature::UnparsedPublicKey` directly without
/// re-parsing.
#[derive(Debug, Clone)]
pub struct CdSigningRoots {
    /// SEC1-uncompressed P-256 public keys (65 bytes each) for each
    /// trusted root.
    public_keys: Vec<Vec<u8>>,
}

impl CdSigningRoots {
    /// Build a trust store seeded with the bundled synthetic CSA-test
    /// CD signing root.
    ///
    /// **Tests and examples only — do not use in production.** Real
    /// commissioners supply CSA-published roots via
    /// [`Self::from_pem`].
    ///
    /// The bundled PEM is a compile-time constant, so parsing it should
    /// never fail at runtime; if it ever does (e.g. someone replaces
    /// the file with garbage), the store is returned empty rather than
    /// panicking, and the verifier will reject every signature with
    /// [`AttestationError::CertificationDeclarationSignatureInvalid`].
    #[must_use]
    pub fn with_csa_test_roots() -> Self {
        let pk = parse_pem_public_key(CSA_TEST_CD_SIGNING_ROOT_PEM).ok();
        Self {
            public_keys: pk.into_iter().collect(),
        }
    }

    /// Build a trust store from PEM-encoded P-256
    /// `SubjectPublicKeyInfo` blobs (one per trusted CSA signing
    /// root).
    ///
    /// # Errors
    ///
    /// Returns [`AttestationError::CertificationDeclarationMalformed`]
    /// if any input fails to parse. An empty slice returns an empty
    /// trust store.
    pub fn from_pem(pems: &[&[u8]]) -> Result<Self, AttestationError> {
        let mut public_keys = Vec::with_capacity(pems.len());
        for raw in pems {
            let pk = parse_pem_public_key(raw)?;
            public_keys.push(pk);
        }
        Ok(Self { public_keys })
    }

    /// Number of trusted roots in the store.
    #[must_use]
    pub fn len(&self) -> usize {
        self.public_keys.len()
    }

    /// Returns `true` if no trusted roots have been loaded.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.public_keys.is_empty()
    }

    /// Internal accessor — borrow the raw 65-byte SEC1 uncompressed
    /// public-key bytes for each trusted root, for the verifier's
    /// signature-check loop.
    fn keys(&self) -> &[Vec<u8>] {
        &self.public_keys
    }
}

/// Verify a Certification Declaration extracted from
/// `attestation_elements` (Matter Core Spec §6.3.1) against a trust
/// store and an expected VID / PID pair.
///
/// Performs five checks in order:
///
/// 1. CMS `SignedData` DER parse via the `cms` crate.
/// 2. Structural validation: a single `SignerInfo`, attached
///    encapsulated content.
/// 3. ECDSA-P256 / SHA-256 signature verification against each
///    trusted root in `trust`; accept on first match.
/// 4. Decode the inner CD TLV.
/// 5. Cross-check declared VID + PID against `expected_vid` /
///    `expected_pid` (sourced from the verified DAC chain by the
///    caller).
///
/// # Errors
///
/// - [`AttestationError::CertificationDeclarationMalformed`] — the
///   CMS DER failed to parse or did not match the expected shape.
/// - [`AttestationError::CertificationDeclarationSignatureInvalid`] —
///   no trusted root accepts the signature.
/// - [`AttestationError::CertificationDeclarationTlvMalformed`] —
///   inner CD TLV missing required fields or malformed.
/// - [`AttestationError::CertificationDeclarationVidMismatch`] —
///   declared VID does not equal `expected_vid`.
/// - [`AttestationError::CertificationDeclarationPidMismatch`] —
///   declared PID list does not contain `expected_pid`.
#[allow(
    clippy::similar_names,
    reason = "the `expected_vid`/`expected_pid` pair mirrors the public-API \
     vocabulary used elsewhere in this crate (VendorId/ProductId); \
     renaming would obscure intent at the call site."
)]
pub fn verify_certification_declaration(
    cd_bytes: &[u8],
    expected_vid: VendorId,
    expected_pid: ProductId,
    trust: &CdSigningRoots,
) -> Result<(), AttestationError> {
    use cms::content_info::ContentInfo;
    use cms::signed_data::SignedData;
    use der::asn1::OctetString;
    use der::{Decode, DecodeValue, Encode, Header, SliceReader, Tag as DerTag};

    // 1. Parse the outer ContentInfo.
    let content_info = ContentInfo::from_der(cd_bytes)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    // ContentInfo.content is an Any wrapping SignedData; re-encode and
    // decode to convert.
    let signed_data_der = content_info
        .content
        .to_der()
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    let signed_data = SignedData::from_der(&signed_data_der)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;

    // 2. Validate shape: exactly one SignerInfo and attached content.
    if signed_data.signer_infos.0.len() != 1 {
        return Err(AttestationError::CertificationDeclarationMalformed);
    }
    let signer = signed_data
        .signer_infos
        .0
        .iter()
        .next()
        .ok_or(AttestationError::CertificationDeclarationMalformed)?;

    // 3. Extract the signed content (the inner CD TLV bytes).
    //
    // `EncapsulatedContentInfo.econtent` is typed `Option<Any>` where
    // the Any wraps an OCTET STRING. We decode the OCTET STRING from
    // the Any's body and copy its bytes — this is the eContent value
    // (the inner CD TLV) the signer signed.
    let econtent = signed_data
        .encap_content_info
        .econtent
        .as_ref()
        .ok_or(AttestationError::CertificationDeclarationMalformed)?;
    // `Any` does not expose its raw value bytes directly; re-encode it
    // then peel off the OCTET STRING tag+length to read the inner
    // bytes via `OctetString::decode_value`.
    let econtent_der = econtent
        .to_der()
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    let mut reader = SliceReader::new(&econtent_der)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    let header = Header::decode(&mut reader)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    if header.tag != DerTag::OctetString {
        return Err(AttestationError::CertificationDeclarationMalformed);
    }
    let octet_string = OctetString::decode_value(&mut reader, header)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;
    let content_bytes = octet_string.as_bytes().to_vec();

    // 4. Extract the signature bytes.
    let sig = signer.signature.as_bytes();

    // 5. Verify ECDSA-P256 / SHA-256 against each trusted root.
    let mut accepted = false;
    for key in trust.keys() {
        if verify_ecdsa_p256_sha256_fixed(key, &content_bytes, sig).is_ok() {
            accepted = true;
            break;
        }
    }
    if !accepted {
        return Err(AttestationError::CertificationDeclarationSignatureInvalid);
    }

    // 6. Decode the inner CD TLV and cross-check VID / PID.
    let parsed = parse_inner_cd_tlv(&content_bytes)?;
    if parsed.vendor_id != expected_vid {
        return Err(AttestationError::CertificationDeclarationVidMismatch {
            declared: parsed.vendor_id,
            expected: expected_vid,
        });
    }
    if !parsed.product_ids.contains(&expected_pid) {
        return Err(AttestationError::CertificationDeclarationPidMismatch(
            expected_pid,
        ));
    }

    Ok(())
}

/// Decoded view of the inner Certification Declaration TLV — the
/// subset the verifier cross-checks today. T30 fleshes out the parser.
#[derive(Debug)]
struct ParsedCd {
    /// Vendor ID (Matter Core Spec §6.3.1 tag 1).
    vendor_id: VendorId,
    /// Product ID list (tag 2 — at least one element required).
    product_ids: Vec<ProductId>,
}

/// Decode the inner CD TLV per Matter Core Spec §6.3.1: an anonymous
/// outer structure with context-tagged fields including tag 1
/// (`vendor_id`, u16) and tag 2 (`product_id_array`, array of u16).
///
/// All other context-tagged fields (`format_version`, `device_type_id`,
/// `certificate_id`, `security_level`, `security_information`,
/// `version_number`, `certification_type`) and any future-extension
/// fields are forward-compat ignored — the verifier only needs VID +
/// PID for cross-checking against the DAC subject.
fn parse_inner_cd_tlv(tlv: &[u8]) -> Result<ParsedCd, AttestationError> {
    use matter_codec::{ContainerKind, Element, Tag, TlvReader, Value};

    let mut reader = TlvReader::new(tlv);
    match reader
        .next()
        .map_err(|_| AttestationError::CertificationDeclarationTlvMalformed)?
    {
        Some(Element::ContainerStart {
            tag: Tag::Anonymous,
            kind: ContainerKind::Structure,
        }) => {}
        _ => return Err(AttestationError::CertificationDeclarationTlvMalformed),
    }

    let mut vid: Option<VendorId> = None;
    let mut pids: Vec<ProductId> = Vec::new();

    loop {
        match reader
            .next()
            .map_err(|_| AttestationError::CertificationDeclarationTlvMalformed)?
        {
            None => return Err(AttestationError::CertificationDeclarationTlvMalformed),
            Some(Element::ContainerEnd) => break,
            Some(Element::Scalar {
                tag: Tag::Context(1),
                value: Value::Uint(v),
            }) => {
                if vid.is_some() {
                    return Err(AttestationError::CertificationDeclarationTlvMalformed);
                }
                let v16 = u16::try_from(v)
                    .map_err(|_| AttestationError::CertificationDeclarationTlvMalformed)?;
                vid = Some(VendorId::new(v16));
            }
            Some(Element::ContainerStart {
                tag: Tag::Context(2),
                kind: ContainerKind::Array,
            }) => {
                if !pids.is_empty() {
                    return Err(AttestationError::CertificationDeclarationTlvMalformed);
                }
                loop {
                    match reader
                        .next()
                        .map_err(|_| AttestationError::CertificationDeclarationTlvMalformed)?
                    {
                        None => return Err(AttestationError::CertificationDeclarationTlvMalformed),
                        Some(Element::ContainerEnd) => break,
                        Some(Element::Scalar {
                            tag: Tag::Anonymous,
                            value: Value::Uint(p),
                        }) => {
                            let p16 = u16::try_from(p).map_err(|_| {
                                AttestationError::CertificationDeclarationTlvMalformed
                            })?;
                            pids.push(ProductId::new(p16));
                        }
                        // Inside the array, unknown shapes are a structural error
                        // (the spec says product IDs are u16). But be lenient on
                        // tagged-not-anonymous in case future M6.x extensions land.
                        Some(_) => {}
                    }
                }
            }
            // Forward-compat: ignore other context-tagged scalars / containers.
            Some(_) => {}
        }
    }

    let vendor_id = vid.ok_or(AttestationError::CertificationDeclarationTlvMalformed)?;
    if pids.is_empty() {
        // product_id_array required to be non-empty per spec §6.3.1.
        return Err(AttestationError::CertificationDeclarationTlvMalformed);
    }
    Ok(ParsedCd {
        vendor_id,
        product_ids: pids,
    })
}

/// Parse a PEM-encoded `SubjectPublicKeyInfo` for a P-256 public key
/// and return the SEC1 uncompressed point (65 bytes:
/// `0x04 || X || Y`) suitable for `ring`'s
/// `UnparsedPublicKey<ECDSA_P256_SHA256_FIXED>`.
///
/// Strips the `-----BEGIN PUBLIC KEY-----` / `-----END PUBLIC KEY-----`
/// armor, base64-decodes the body, and slices the trailing 65 bytes of
/// the DER (the SEC1 uncompressed point inside the SPKI's `BIT
/// STRING`). The point's `0x04` marker byte is checked here; ring's
/// `UnparsedPublicKey` rejects any malformed point at signature-verify
/// time as a second line of defense.
fn parse_pem_public_key(pem: &[u8]) -> Result<Vec<u8>, AttestationError> {
    use base64::Engine;

    const HEADER: &str = "-----BEGIN PUBLIC KEY-----";
    const FOOTER: &str = "-----END PUBLIC KEY-----";

    let pem_str = std::str::from_utf8(pem)
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;

    let header_start = pem_str
        .find(HEADER)
        .ok_or(AttestationError::CertificationDeclarationMalformed)?;
    let body_start = header_start + HEADER.len();
    let footer_start = pem_str
        .find(FOOTER)
        .ok_or(AttestationError::CertificationDeclarationMalformed)?;
    if footer_start <= body_start {
        return Err(AttestationError::CertificationDeclarationMalformed);
    }

    // Strip all whitespace from the base64 body.
    let body: String = pem_str[body_start..footer_start]
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect();

    let der = base64::engine::general_purpose::STANDARD
        .decode(body.as_bytes())
        .map_err(|_| AttestationError::CertificationDeclarationMalformed)?;

    // Extract the SEC1 uncompressed point from the SubjectPublicKeyInfo.
    // The structure for a P-256 SPKI is exactly 91 bytes:
    //   30 59                        SEQUENCE (89)
    //   30 13                          SEQUENCE (19)
    //     06 07 2A 86 48 CE 3D 02 01   OID ecPublicKey
    //     06 08 2A 86 48 CE 3D 03 01 07 OID prime256v1
    //   03 42 00                       BIT STRING (66 bytes, 0 unused bits)
    //   04 XX...XX                     SEC1 uncompressed point (65 bytes)
    //                                  starting with 0x04
    //
    // The SEC1 point is the last 65 bytes. We validate the marker byte
    // and let `ring::UnparsedPublicKey::new` reject malformed bytes
    // later if the prefix is corrupt.
    if der.len() < 65 {
        return Err(AttestationError::CertificationDeclarationMalformed);
    }
    let point = &der[der.len() - 65..];
    if point[0] != 0x04 {
        return Err(AttestationError::CertificationDeclarationMalformed);
    }
    Ok(point.to_vec())
}

/// Verify an ECDSA-P256 / SHA-256 signature in fixed (raw r||s, 64
/// bytes) form against a SEC1-uncompressed P-256 public key.
///
/// Maps any verification failure to
/// [`AttestationError::CertificationDeclarationSignatureInvalid`] —
/// the caller (the per-root loop in
/// [`verify_certification_declaration`]) only cares whether *some*
/// trusted root accepted the signature, not which one rejected it.
fn verify_ecdsa_p256_sha256_fixed(
    public_key: &[u8],
    msg: &[u8],
    sig: &[u8],
) -> Result<(), AttestationError> {
    use ring::signature::{UnparsedPublicKey, ECDSA_P256_SHA256_FIXED};
    let pk = UnparsedPublicKey::new(&ECDSA_P256_SHA256_FIXED, public_key);
    pk.verify(msg, sig)
        .map_err(|_| AttestationError::CertificationDeclarationSignatureInvalid)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn with_csa_test_roots_loads_bundled_root() {
        let trust = CdSigningRoots::with_csa_test_roots();
        assert_eq!(trust.len(), 1);
        assert!(!trust.is_empty());
    }

    #[test]
    #[allow(clippy::expect_used)] // Test-code carve-out: see CLAUDE.md.
    fn parse_pem_public_key_extracts_65_byte_sec1_point() {
        const PEM: &[u8] = include_bytes!("./csa_cd_signing_roots/csa-test-cd-signing-root.pem");
        let key = parse_pem_public_key(PEM).expect("happy path parses");
        assert_eq!(key.len(), 65, "SEC1 uncompressed P-256 point");
        assert_eq!(key[0], 0x04, "uncompressed-point marker byte");
    }

    #[test]
    #[allow(clippy::expect_used)] // Test-code carve-out: see CLAUDE.md.
    fn parse_pem_public_key_rejects_garbage() {
        let err = parse_pem_public_key(b"not a PEM").expect_err("garbage rejected");
        assert!(matches!(
            err,
            AttestationError::CertificationDeclarationMalformed
        ));
    }

    #[test]
    #[allow(clippy::unwrap_used)] // Test-code carve-out: see CLAUDE.md.
    fn from_pem_empty_input_yields_empty_trust_store() {
        let trust = CdSigningRoots::from_pem(&[]).unwrap();
        assert!(trust.is_empty());
        assert_eq!(trust.len(), 0);
    }

    #[test]
    fn parse_inner_cd_tlv_extracts_vendor_id_and_pid_list() {
        // Test-code carve-out: see CLAUDE.md.
        #![allow(clippy::unwrap_used, clippy::expect_used)]
        use matter_codec::{Tag, TlvWriter};
        let mut buf = Vec::new();
        let mut w = TlvWriter::new(&mut buf);
        w.start_structure(Tag::Anonymous).unwrap();
        w.put_uint(Tag::Context(0), 1).unwrap(); // format_version
        w.put_uint(Tag::Context(1), 0xFFF1).unwrap(); // vendor_id
        w.start_array(Tag::Context(2)).unwrap();
        w.put_uint(Tag::Anonymous, 0x8001).unwrap();
        w.put_uint(Tag::Anonymous, 0x8002).unwrap();
        w.end_container().unwrap(); // close array
        w.end_container().unwrap(); // close struct

        let parsed = parse_inner_cd_tlv(&buf).expect("happy path decodes");
        assert_eq!(parsed.vendor_id, VendorId::new(0xFFF1));
        assert_eq!(
            parsed.product_ids,
            vec![ProductId::new(0x8001), ProductId::new(0x8002)]
        );
    }

    #[test]
    fn parse_inner_cd_tlv_ignores_forward_compat_fields() {
        // Test-code carve-out: see CLAUDE.md.
        #![allow(clippy::unwrap_used, clippy::expect_used)]
        use matter_codec::{Tag, TlvWriter};
        // Hand-roll a CD with tag 0 (format_version), tag 1 (vid), tag 2 (pids),
        // tag 3 (device_type_id), tag 4 (certificate_id utf8), tag 5..8 (security_*,
        // version_number, certification_type), AND a fake tag 99 (future field).
        let mut buf = Vec::new();
        let mut w = TlvWriter::new(&mut buf);
        w.start_structure(Tag::Anonymous).unwrap();
        w.put_uint(Tag::Context(0), 1).unwrap();
        w.put_uint(Tag::Context(1), 0xFFF1).unwrap();
        w.start_array(Tag::Context(2)).unwrap();
        w.put_uint(Tag::Anonymous, 0x8001).unwrap();
        w.end_container().unwrap();
        w.put_uint(Tag::Context(3), 0x0100).unwrap();
        w.put_utf8(Tag::Context(4), "CSA-ID").unwrap();
        w.put_uint(Tag::Context(5), 0).unwrap();
        w.put_uint(Tag::Context(6), 0).unwrap();
        w.put_uint(Tag::Context(7), 1).unwrap();
        w.put_uint(Tag::Context(8), 0).unwrap();
        w.put_uint(Tag::Context(99), 0xDEAD).unwrap(); // unknown future field
        w.end_container().unwrap();

        let parsed = parse_inner_cd_tlv(&buf).expect("forward-compat decode");
        assert_eq!(parsed.vendor_id, VendorId::new(0xFFF1));
        assert_eq!(parsed.product_ids, vec![ProductId::new(0x8001)]);
    }

    #[test]
    fn parse_inner_cd_tlv_rejects_missing_vid() {
        // Test-code carve-out: see CLAUDE.md.
        #![allow(clippy::unwrap_used, clippy::expect_used)]
        use matter_codec::{Tag, TlvWriter};
        let mut buf = Vec::new();
        let mut w = TlvWriter::new(&mut buf);
        w.start_structure(Tag::Anonymous).unwrap();
        // No tag 1 (vendor_id).
        w.start_array(Tag::Context(2)).unwrap();
        w.put_uint(Tag::Anonymous, 0x8001).unwrap();
        w.end_container().unwrap();
        w.end_container().unwrap();

        let err = parse_inner_cd_tlv(&buf).expect_err("missing vid rejected");
        assert!(matches!(
            err,
            AttestationError::CertificationDeclarationTlvMalformed
        ));
    }

    #[test]
    fn parse_inner_cd_tlv_rejects_garbage() {
        // Test-code carve-out: see CLAUDE.md.
        #![allow(clippy::unwrap_used, clippy::expect_used)]
        let err = parse_inner_cd_tlv(&[0xFF]).expect_err("garbage rejected");
        assert!(matches!(
            err,
            AttestationError::CertificationDeclarationTlvMalformed
        ));
    }
}
