//! Byte-parity / roundtrip-floor vectors for the OTA Provider command path.
//!
//! ## What this proves (F1)
//!
//! A `QueryImage` flows through the **full server-side IM path** — a client
//! `InvokeRequestMessage` ([`build_invoke_request`] + the generated
//! [`encode_query_image`](prov::encode_query_image)) is decoded by
//! [`parse_invoke_request`], the decoded command-fields drive
//! [`handle_query_image`], the result is framed by
//! [`build_invoke_response_command`], and that `InvokeResponseMessage` decodes
//! back via [`parse_invoke_response`] + the generated `QueryImageResponse::decode`
//! to the expected fields. This exercises Tasks 1–4 composed through the real IM
//! envelope, and freezes the **command-fields TLV** (the cluster-level wire) as
//! hex so an accidental tag/type/layout change is caught in review.
//!
//! ## The gap (deferred to F4, by design)
//!
//! These vectors are the **roundtrip floor** the plan names: they are
//! self-generated by our own client+server codecs, **not** captured from chip's
//! `ota-provider-app` ↔ `ota-requestor-app`. Capturing the decrypted,
//! CASE-encrypted `QueryImage`/`QueryImageResponse` bytes from the reference apps
//! needs both apps plus a decrypted-payload extraction path and is impractical at
//! F1 (no connectedhomeip checkout in this environment). Per the F design the
//! **live `ota-requestor-app` is the PRIMARY wire oracle** and arrives in F4: it
//! rejects a malformed `QueryImageResponse`/BDX, so a successful
//! announce→query→download→apply is itself strong wire evidence. Until then the
//! frozen hex below guards against wire-layout drift.
//!
//! The frozen command-fields hex was emitted by the codecs under test and
//! verified field-by-field below; it is **not** an independent oracle. The IM
//! envelope itself is already byte-parity-tested against matter.js in
//! `matter-interaction`, so only the OTA cluster-level fields are frozen here.

#![allow(clippy::unwrap_used, clippy::expect_used)]
// Test code: CLAUDE.md carve-out.
// The field-by-field wire-layout doc comments name spec fields (VendorID,
// UpdateToken, …) in prose alongside hex; backticking each is noise here.
#![allow(clippy::doc_markdown)]

use matter_clusters::gen::ota_software_update_provider as prov;
use matter_interaction::{
    build_invoke_request, build_invoke_response_command, parse_invoke_request,
    parse_invoke_response, CommandPath, InvokeResponse,
};
use matter_ota::{handle_query_image, ImageOffer};
use prov::{DownloadProtocolEnum, StatusEnum};

/// Fixed `QueryImage` request inputs (a requestor on software v1 asking for an
/// image over BDX). Frozen so the command-fields hex is reproducible.
const VENDOR_ID: u16 = 0xFFF1;
const PRODUCT_ID: u16 = 0x8000;
const CURRENT_VERSION: u32 = 1;

/// The `QueryImage` command-fields struct (anonymous TLV), as produced by the
/// generated client encoder. Field-by-field (TLV control byte · tag · value):
///   `15`            anon structure start
///   `25 00 f1 ff`   ctx0 VendorID  uint16 = 0xFFF1
///   `25 01 00 80`   ctx1 ProductID uint16 = 0x8000
///   `24 02 01`      ctx2 SoftwareVersion uint8 = 1
///   `36 03`         ctx3 ProtocolsSupported array start
///     `04 00`         anonymous uint8 = 0 (BdxSynchronous)
///   `18`            array end
///   `18`            structure end
const QUERY_IMAGE_FIELDS_HEX: &str = "152500f1ff25010080240201360304001818";

/// The `QueryImageResponse` command-fields struct (anonymous TLV) for
/// [`offer()`], `Status = UpdateAvailable`. Field-by-field:
///   `15`                   anon structure start
///   `24 00 00`             ctx0 Status uint8 = 0 (UpdateAvailable)
///   `2c 02 1d <29 bytes>`  ctx2 ImageURI utf8 (len 0x1d = 29) "bdx://…/fw.ota"
///   `24 03 02`             ctx3 SoftwareVersion uint8 = 2
///   `2c 04 03 32 2e 30`    ctx4 SoftwareVersionString utf8 "2.0"
///   `30 05 04 de ad be ef` ctx5 UpdateToken byte-string[4]
///   `18`                   structure end
const QUERY_IMAGE_RESPONSE_FIELDS_HEX: &str = concat!(
    "15",                                                               // anon structure start
    "240000", // ctx0 Status = UpdateAvailable
    "2c021d6264783a2f2f303030303030303030303030303034322f66772e6f7461", // ctx2 ImageURI
    "240302", // ctx3 SoftwareVersion = 2
    "2c0403322e30", // ctx4 SoftwareVersionString = "2.0"
    "300504deadbeef", // ctx5 UpdateToken
    "18",     // structure end
);

fn offer() -> ImageOffer {
    ImageOffer {
        software_version: 2,
        software_version_string: "2.0".into(),
        image_uri: "bdx://0000000000000042/fw.ota".into(),
        update_token: vec![0xDE, 0xAD, 0xBE, 0xEF],
    }
}

/// Strip ASCII whitespace from a (possibly grouped) hex literal and decode it.
fn unhex(s: &str) -> Vec<u8> {
    let compact: String = s.chars().filter(|c| !c.is_ascii_whitespace()).collect();
    hex::decode(compact).expect("valid hex literal")
}

#[test]
fn query_image_request_full_im_path_and_frozen_fields() {
    // A client builds the QueryImage InvokeRequest exactly as a Requestor would.
    let protocols = vec![DownloadProtocolEnum::BdxSynchronous];
    let fields = prov::encode_query_image(
        VENDOR_ID,
        PRODUCT_ID,
        CURRENT_VERSION,
        &protocols,
        None,
        None,
        None,
        None,
    );
    // Frozen command-fields wire (the part a chip capture would compare).
    assert_eq!(
        fields,
        unhex(QUERY_IMAGE_FIELDS_HEX),
        "QueryImage command-fields TLV drifted from the frozen vector"
    );

    let path = CommandPath {
        endpoint: 0,
        cluster: prov::CLUSTER_ID,
        command: prov::command_id::QUERY_IMAGE,
    };
    let request_msg = build_invoke_request(path, &fields);

    // Server side: decode the inbound InvokeRequest and confirm the path + the
    // captured command-fields blob are exactly what the client sent.
    let parsed = parse_invoke_request(&request_msg).expect("parse invoke request");
    assert_eq!(parsed.commands.len(), 1);
    assert_eq!(parsed.commands[0].path, path);
    assert_eq!(parsed.commands[0].fields_tlv, fields);
}

#[test]
fn query_image_response_full_im_path_and_frozen_fields() {
    // Drive the handler with the same request the requestor sent.
    let protocols = vec![DownloadProtocolEnum::BdxSynchronous];
    let request_fields = prov::encode_query_image(
        VENDOR_ID,
        PRODUCT_ID,
        CURRENT_VERSION,
        &protocols,
        None,
        None,
        None,
        None,
    );
    let offer = offer();
    let response_fields = handle_query_image(&request_fields, Some(&offer)).expect("handle");

    // Frozen response command-fields wire.
    assert_eq!(
        response_fields,
        unhex(QUERY_IMAGE_RESPONSE_FIELDS_HEX),
        "QueryImageResponse command-fields TLV drifted from the frozen vector"
    );

    // Frame it as a real InvokeResponseMessage and decode the whole way back —
    // proving T3 (build_invoke_response_command) + the generated response decoder
    // agree end to end.
    let path = CommandPath {
        endpoint: 0,
        cluster: prov::CLUSTER_ID,
        command: prov::command_id::QUERY_IMAGE_RESPONSE,
    };
    let response_msg = build_invoke_response_command(path, &response_fields);
    match parse_invoke_response(&response_msg).expect("parse invoke response") {
        InvokeResponse::Command {
            path: p,
            fields_tlv,
        } => {
            assert_eq!(p, path);
            let decoded = prov::QueryImageResponse::decode(&fields_tlv).expect("decode response");
            assert_eq!(decoded.status, StatusEnum::UpdateAvailable);
            assert_eq!(decoded.image_uri.as_deref(), Some(offer.image_uri.as_str()));
            assert_eq!(decoded.software_version, Some(offer.software_version));
            assert_eq!(
                decoded.software_version_string.as_deref(),
                Some(offer.software_version_string.as_str())
            );
            assert_eq!(
                decoded.update_token.as_deref(),
                Some(&offer.update_token[..])
            );
        }
        InvokeResponse::Status(s) => panic!("expected a response command, got Status({s:?})"),
    }
}
