//! String-building emitter for the uniform cluster module shape (spec §2).
//!
//! Plain `String` building with an indent helper — no template engine (the
//! CHIP codegen's templating is the cautionary tale the spec cites). Output
//! is later normalized by rustfmt, so we optimise for correctness, not
//! whitespace.

use crate::codegen::model::{Choice, Cluster, Datatype, FieldDef};
use crate::codegen::rustgen::types::{base_type, ident, rust_type, screaming, snake, Position};
use std::collections::HashSet;
use std::fmt::Write as _;

/// The rustdoc sentence on every generated item the specification marks
/// provisional (`FieldDef::provisional` and its siblings; M9-A3 B4).
pub(crate) const PROVISIONAL_DOC: &str =
    "Provisional in the Matter specification: a later revision may change or remove it.";

/// One rustdoc sentence per choice-conformance group among `fields`, in the
/// order the groups first appear (M9-A3 B4): the generated types take every
/// field of a group as an `Option`, so the rule "exactly one" (`O.a`) or "at
/// least one" (`O.a+`) is stated, not enforced. Field names are the generated
/// Rust identifiers.
pub(crate) fn choice_docs(fields: &[FieldDef]) -> Vec<String> {
    let mut groups: Vec<(&Choice, Vec<String>)> = Vec::new();
    for f in fields {
        let Some(choice) = &f.choice else { continue };
        let name = format!("`{}`", ident(&snake(&f.name)));
        match groups.iter_mut().find(|(c, _)| c.group == choice.group) {
            Some((_, names)) => names.push(name),
            None => groups.push((choice, vec![name])),
        }
    }
    groups
        .into_iter()
        .map(|(c, names)| {
            let how = if c.or_more {
                "at least"
            } else if c.or_less {
                "at most"
            } else {
                "exactly"
            };
            let count = if c.count == 1 {
                "one".to_string()
            } else {
                c.count.to_string()
            };
            format!(
                "Choice group `{}`: a sender includes {how} {count} of {}. Not checked when encoding.",
                c.group,
                names.join(", ")
            )
        })
        .collect()
}

/// Emit the full Rust module source for one cluster.
#[must_use]
pub fn generate_cluster(c: &Cluster) -> String {
    let mut s = String::new();
    emit_header(&mut s, c);
    emit_ids(&mut s, c);
    emit_feature_bitflags(&mut s, c);
    // Structs reachable from a request command are built by callers (to encode),
    // so their declaration must stay constructible (no `#[non_exhaustive]`).
    let dts = c.datatypes.iter().map(|d| (d.name.as_str(), d)).collect();
    let encode_reachable = super::emit_codecs::command_encode_reachable_structs(c, &dts);
    for d in &c.datatypes {
        emit_datatype(&mut s, d, &encode_reachable);
    }
    super::emit_codecs::emit_codecs(&mut s, c);
    s
}

/// Emit the shared globals module (`gen/globals.rs`). IDs + generic decoders
/// generated once; per-cluster typed interpretation composes on top.
#[must_use]
pub fn generate_globals() -> String {
    let mut s = String::new();
    s.push_str(
        "//! Global attributes present on every cluster (Matter spec §7.13).\n\
         //! @generated by `cargo xtask codegen` — do not edit.\n\n\
         #![allow(clippy::all, clippy::pedantic, dead_code, unreachable_pub, unused_imports)]\n\n\
         use crate::error::ClusterError;\n\
         use matter_codec::{Element, TlvReader, Value};\n\n\
         /// FeatureMap (0xFFFC).\n\
         pub const FEATURE_MAP: u32 = 0xFFFC;\n\
         /// ClusterRevision (0xFFFD).\n\
         pub const CLUSTER_REVISION: u32 = 0xFFFD;\n\
         /// AttributeList (0xFFFB).\n\
         pub const ATTRIBUTE_LIST: u32 = 0xFFFB;\n\
         /// AcceptedCommandList (0xFFF9).\n\
         pub const ACCEPTED_COMMAND_LIST: u32 = 0xFFF9;\n\
         /// GeneratedCommandList (0xFFF8).\n\
         pub const GENERATED_COMMAND_LIST: u32 = 0xFFF8;\n\n",
    );
    s.push_str(
        "/// Decode a FeatureMap / any `u32` global attribute value.\n\
         ///\n\
         /// # Errors\n\
         /// Returns [`ClusterError`] if the element is not an unsigned int.\n\
         pub fn decode_u32(tlv: &[u8]) -> Result<u32, ClusterError> {\n\
         \x20   let mut r = TlvReader::new(tlv);\n\
         \x20   match r.next()? {\n\
         \x20       Some(Element::Scalar { value: Value::Uint(v), .. }) => {\n\
         \x20           u32::try_from(v).map_err(|_| ClusterError::InvalidLength(\"global u32\"))\n\
         \x20       }\n\
         \x20       _ => Err(ClusterError::UnexpectedType { context: \"global u32\" }),\n\
         \x20   }\n\
         }\n",
    );
    s
}

/// `writeln!` into the buffer (the `Vec`/`String` formatter is infallible).
macro_rules! line {
    ($s:expr, $($arg:tt)*) => {{
        let _ = writeln!($s, $($arg)*);
    }};
}
#[allow(unused_imports)]
pub(crate) use line;

fn emit_header(s: &mut String, c: &Cluster) {
    line!(s, "//! {} cluster (0x{:04X}).", c.name, c.id);
    line!(
        s,
        "//! @generated by `cargo xtask codegen` — do not edit.\n"
    );
    line!(
        s,
        "#![allow(clippy::all, clippy::pedantic, dead_code, unreachable_pub, unused_imports)]\n"
    );
    if !defines_local_semantic_tag_struct(c) {
        line!(s, "use crate::datatypes::SemanticTagStruct;");
    }
    line!(s, "use crate::error::ClusterError;");
    line!(s, "use crate::types::Nullable;");
    line!(
        s,
        "use matter_codec::{{ContainerKind, Element, Tag, TlvReader, TlvWriter, Value}};\n"
    );
    line!(s, "/// Cluster ID.");
    line!(s, "pub const CLUSTER_ID: u32 = 0x{:04X};", c.id);
    line!(s, "/// Cluster revision.");
    line!(s, "pub const CLUSTER_REVISION: u16 = {};\n", c.revision);
}

/// True when the cluster defines its own `SemanticTagStruct` datatype, so the
/// module must not import the hand-written global one (the `semtag` struct,
/// `crate::datatypes::SemanticTagStruct`): the two names would collide
/// (E0255). `ModeSelect` is the case: its cluster-local `SemanticTagStruct`
/// (`MfgCode`, `Value`; 1.4.2 `ModeSelect.xml`) is a different struct from the
/// global `semtag` (`MfgCode`, `NamespaceID`, `Tag`, `Label`).
///
/// # Panics
///
/// At codegen time, if such a cluster also references `semtag`: without the
/// import, `SemanticTagStruct` would silently name the local struct there.
fn defines_local_semantic_tag_struct(c: &Cluster) -> bool {
    if !c.datatypes.iter().any(|d| d.name == "SemanticTagStruct") {
        return false;
    }
    let refs_semtag = |ty: &str, entry: Option<&str>| ty == "semtag" || entry == Some("semtag");
    let mut fields = c
        .commands
        .iter()
        .flat_map(|cmd| &cmd.fields)
        .chain(c.events.iter().flat_map(|e| &e.fields))
        .chain(c.datatypes.iter().flat_map(|d| &d.fields));
    let uses_global = c
        .attributes
        .iter()
        .any(|a| refs_semtag(&a.ty, a.entry_type.as_deref()))
        || fields.any(|f| refs_semtag(&f.ty, f.entry_type.as_deref()));
    assert!(
        !uses_global,
        "codegen: {} defines its own SemanticTagStruct and also references the global \
         `semtag`; the two would share one name — rename one before allowlisting it",
        c.name
    );
    true
}

fn emit_ids(s: &mut String, c: &Cluster) {
    line!(s, "/// Command IDs (requests and responses).");
    line!(s, "pub mod command_id {{");
    for cmd in &c.commands {
        line!(s, "    /// `{}` ({}).", cmd.name, cmd.direction);
        if cmd.provisional {
            line!(s, "    /// {PROVISIONAL_DOC}");
        }
        line!(
            s,
            "    pub const {}: u32 = 0x{:02X};",
            screaming(&cmd.name),
            cmd.id
        );
    }
    line!(s, "}}\n");

    line!(s, "/// Attribute IDs (cluster-specific).");
    line!(s, "pub mod attribute_id {{");
    for a in &c.attributes {
        line!(s, "    /// `{}`.", a.name);
        if a.provisional {
            line!(s, "    /// {PROVISIONAL_DOC}");
        }
        line!(
            s,
            "    pub const {}: u32 = 0x{:04X};",
            screaming(&a.name),
            a.id
        );
    }
    line!(s, "}}\n");

    // Emitted only when the cluster has dumped events, so clusters without
    // them keep their exact previous output (no empty `event_id` churn).
    if !c.events.is_empty() {
        line!(s, "/// Event IDs.");
        line!(s, "pub mod event_id {{");
        for ev in &c.events {
            line!(s, "    /// `{}` ({} priority).", ev.name, ev.priority);
            if ev.provisional {
                line!(s, "    /// {PROVISIONAL_DOC}");
            }
            line!(
                s,
                "    pub const {}: u32 = 0x{:02X};",
                screaming(&ev.name),
                ev.id
            );
        }
        line!(s, "}}\n");
    }
}

fn emit_feature_bitflags(s: &mut String, c: &Cluster) {
    if c.features.is_empty() {
        return;
    }
    line!(s, "bitflags::bitflags! {{");
    line!(s, "    /// `{}` feature bits (FeatureMap).", c.name);
    line!(s, "    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]");
    line!(s, "    pub struct Feature: u32 {{");
    for f in &c.features {
        line!(s, "        /// {} ({}).", f.name, f.code);
        if f.provisional {
            line!(s, "        /// {PROVISIONAL_DOC}");
        }
        line!(s, "        const {} = 1 << {};", screaming(&f.code), f.bit);
    }
    line!(s, "    }}");
    line!(s, "}}\n");
}

fn emit_datatype(s: &mut String, d: &Datatype, encode_reachable: &HashSet<&str>) {
    match d.kind.as_str() {
        "enum" => emit_enum(s, d),
        "bitmap" => emit_bitmap(s, d),
        "struct" => emit_struct(s, d, encode_reachable),
        _ => {} // "scalar": a named alias of a primitive — referenced inline, no decl needed.
    }
}

fn enum_backing(base: &str) -> &'static str {
    if base == "enum16" {
        "u16"
    } else {
        "u8"
    }
}

/// The catch-all "unknown discriminant" variant name for a generated enum.
///
/// Normally `Unknown`, but some Matter enums (`AirQualityEnum`, `PowerModeEnum`,
/// `BatChargeStateEnum`, …) define a member literally named `Unknown`; for those
/// the catch-all becomes `Unrecognized` so the two do not collide. Panics only
/// if a model defines BOTH `Unknown` and `Unrecognized` members (no known Matter
/// enum does) — a loud failure, never a silent miscompile.
fn catch_all_variant(d: &Datatype) -> &'static str {
    let has = |n: &str| d.values.iter().any(|v| v.name == n);
    if !has("Unknown") {
        "Unknown"
    } else if !has("Unrecognized") {
        "Unrecognized"
    } else {
        panic!(
            "enum {} defines both Unknown and Unrecognized members",
            d.name
        )
    }
}

fn emit_enum(s: &mut String, d: &Datatype) {
    let backing = enum_backing(&d.base);
    let catch_all = catch_all_variant(d);
    line!(s, "/// `{}` ({}).", d.name, d.base);
    line!(s, "#[derive(Copy, Clone, Debug, PartialEq, Eq)]");
    // Members like `4V5`/`523` (PowerSource BatCommonDesignationEnum) get an
    // `_`-prefixed variant name (see `ident`), which is not upper-camel-case.
    if d.values
        .iter()
        .any(|v| v.name.chars().next().is_some_and(|c| c.is_ascii_digit()))
    {
        line!(s, "#[allow(non_camel_case_types)]");
    }
    line!(s, "pub enum {} {{", d.name);
    for v in &d.values {
        line!(s, "    /// {} = {}.", v.name, v.value);
        line!(s, "    {},", ident(&v.name));
    }
    line!(s, "    /// A value not known to this codegen revision.");
    line!(s, "    {catch_all}({backing}),");
    line!(s, "}}\n");

    line!(s, "impl {} {{", d.name);
    line!(
        s,
        "    /// Decode from its raw discriminant (unknown → `{catch_all}`)."
    );
    line!(s, "    #[must_use]");
    line!(s, "    pub fn from_raw(v: {backing}) -> Self {{");
    line!(s, "        match v {{");
    for v in &d.values {
        line!(s, "            {} => Self::{},", v.value, ident(&v.name));
    }
    line!(s, "            other => Self::{catch_all}(other),");
    line!(s, "        }}");
    line!(s, "    }}");
    line!(s, "    /// The raw discriminant.");
    line!(s, "    #[must_use]");
    line!(s, "    pub fn to_raw(self) -> {backing} {{");
    line!(s, "        match self {{");
    for v in &d.values {
        line!(s, "            Self::{} => {},", ident(&v.name), v.value);
    }
    line!(s, "            Self::{catch_all}(v) => v,");
    line!(s, "        }}");
    line!(s, "    }}");
    line!(s, "}}\n");
}

fn emit_bitmap(s: &mut String, d: &Datatype) {
    let backing = match d.base.as_str() {
        "map16" => "u16",
        "map32" => "u32",
        _ => "u8",
    };
    line!(s, "bitflags::bitflags! {{");
    line!(s, "    /// `{}` ({}).", d.name, d.base);
    line!(s, "    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]");
    line!(s, "    pub struct {}: {} {{", d.name, backing);
    for b in &d.bits {
        if let Some(bit) = b.bit {
            line!(s, "        /// {}.", b.name);
            line!(s, "        const {} = 1 << {};", screaming(&b.name), bit);
        }
    }
    line!(s, "    }}");
    line!(s, "}}\n");
}

fn emit_struct(s: &mut String, d: &Datatype, encode_reachable: &HashSet<&str>) {
    line!(s, "/// `{}` struct.", d.name);
    if let Some(global) = &d.global_name {
        line!(s, "///");
        line!(s, "/// Generated from the Matter global type `{global}`.");
    }
    for doc in choice_docs(&d.fields) {
        line!(s, "///");
        line!(s, "/// {doc}");
    }
    line!(s, "#[derive(Clone, Debug, PartialEq)]");
    // `#[non_exhaustive]` future-proofs decode-only data structs, but blocks the
    // struct-literal construction that command-encode callers need; skip it for
    // structs reachable from a request command (they are built to be encoded).
    if !encode_reachable.contains(d.name.as_str()) {
        line!(s, "#[non_exhaustive]");
    }
    line!(s, "pub struct {} {{", d.name);
    let fabric_scoped = super::emit_codecs::struct_is_fabric_scoped(d);
    for f in &d.fields {
        let ty = rust_type(
            &f.ty,
            f.entry_type.as_deref(),
            f.nullable,
            f.optional,
            Position::Field,
        );
        line!(s, "    /// Field {} (tag {}).", f.name, f.id);
        if f.provisional {
            line!(s, "    /// {PROVISIONAL_DOC}");
        }
        if fabric_scoped && f.fabric_sensitive {
            line!(
                s,
                "    /// Fabric-sensitive: `None` when the device withheld it because the entry"
            );
            line!(s, "    /// belongs to another fabric (unfiltered read).");
        }
        // Escape reserved-word field names (`Type` -> `r#type`); see field_ident
        // in emit_codecs (the codec pass uses the same rule).
        line!(s, "    pub {}: {},", ident(&snake(&f.name)), ty);
    }
    line!(s, "}}\n");
    // The struct's encode/decode impls are emitted by the codec pass (next
    // task), since they share the scalar read/write helpers.
    let _ = base_type; // keep import used regardless of branch
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::model::{Datatype, EnumValue};

    fn enum_dt(name: &str, base: &str, values: &[(u32, &str)]) -> Datatype {
        Datatype {
            name: name.to_string(),
            base: base.to_string(),
            kind: "enum".to_string(),
            values: values
                .iter()
                .map(|(v, n)| EnumValue {
                    value: *v,
                    name: (*n).to_string(),
                })
                .collect(),
            bits: vec![],
            fields: vec![],
            global_name: None,
        }
    }

    #[test]
    fn enum_without_unknown_member_keeps_unknown_catch_all() {
        let mut s = String::new();
        emit_enum(
            &mut s,
            &enum_dt("StartUpOnOffEnum", "enum8", &[(0, "Off"), (1, "On")]),
        );
        assert!(
            s.contains("Unknown(u8),"),
            "expected Unknown catch-all:\n{s}"
        );
        assert!(s.contains("other => Self::Unknown(other),"), "{s}");
        assert!(s.contains("Self::Unknown(v) => v,"), "{s}");
    }

    #[test]
    fn enum_with_unknown_member_uses_unrecognized_catch_all() {
        let mut s = String::new();
        emit_enum(
            &mut s,
            &enum_dt("AirQualityEnum", "enum8", &[(0, "Unknown"), (1, "Good")]),
        );
        // The model member stays `Unknown` (a fieldless variant); the catch-all
        // is renamed to `Unrecognized` to avoid a duplicate-variant collision.
        assert!(
            s.contains("    Unknown,\n"),
            "model member Unknown missing:\n{s}"
        );
        assert!(
            s.contains("Unrecognized(u8),"),
            "catch-all not renamed:\n{s}"
        );
        assert!(
            !s.contains("Unknown(u8)"),
            "colliding catch-all present:\n{s}"
        );
        assert!(s.contains("other => Self::Unrecognized(other),"), "{s}");
        assert!(s.contains("Self::Unrecognized(v) => v,"), "{s}");
    }

    #[test]
    fn fabric_sensitive_field_doc_says_none_means_withheld() {
        use crate::codegen::model::FieldDef;
        let f = |id: u32, name: &str, sensitive: bool| FieldDef {
            id,
            name: name.to_string(),
            ty: "uint16".to_string(),
            metatype: "integer".to_string(),
            entry_type: None,
            nullable: false,
            optional: sensitive,
            fabric_sensitive: sensitive,
            mandatory_on_write: false,
            provisional: false,
            choice: None,
        };
        let d = Datatype {
            name: "ScopedStruct".to_string(),
            base: "struct".to_string(),
            kind: "struct".to_string(),
            values: vec![],
            bits: vec![],
            fields: vec![
                f(1, "Secret", true),
                f(2, "Plain", false),
                f(254, "FabricIndex", false),
            ],
            global_name: None,
        };
        let mut s = String::new();
        emit_struct(&mut s, &d, &HashSet::new());
        assert_eq!(s.matches("Fabric-sensitive: `None`").count(), 1, "{s}");
        assert!(s.contains("pub secret: Option<u16>,"), "{s}");
        assert!(s.contains("pub plain: u16,"), "{s}");
    }

    fn cluster_with(
        datatypes: Vec<Datatype>,
        attributes: Vec<crate::codegen::model::Attribute>,
    ) -> Cluster {
        Cluster {
            id: 0x0050,
            name: "Shadowing".to_string(),
            revision: 1,
            features: vec![],
            attributes,
            commands: vec![],
            events: vec![],
            datatypes,
        }
    }

    fn struct_dt(name: &str) -> Datatype {
        Datatype {
            name: name.to_string(),
            base: "struct".to_string(),
            kind: "struct".to_string(),
            values: vec![],
            bits: vec![],
            fields: vec![],
            global_name: None,
        }
    }

    #[test]
    fn global_semantic_tag_import_is_kept_unless_a_local_struct_shadows_it() {
        const IMPORT: &str = "use crate::datatypes::SemanticTagStruct;";
        let mut plain = String::new();
        emit_header(&mut plain, &cluster_with(vec![], vec![]));
        assert!(plain.contains(IMPORT), "{plain}");
        // ModeSelect's shape: a cluster-local struct of the same name.
        let mut shadowed = String::new();
        emit_header(
            &mut shadowed,
            &cluster_with(vec![struct_dt("SemanticTagStruct")], vec![]),
        );
        assert!(!shadowed.contains(IMPORT), "{shadowed}");
    }

    #[test]
    #[should_panic(expected = "defines its own SemanticTagStruct and also references")]
    fn a_local_semantic_tag_struct_next_to_a_semtag_reference_stops_codegen() {
        use crate::codegen::model::Attribute;
        let tag_list = Attribute {
            id: 0,
            name: "TagList".to_string(),
            ty: "list".to_string(),
            metatype: "array".to_string(),
            entry_type: Some("semtag".to_string()),
            nullable: false,
            optional: false,
            writable: false,
            provisional: false,
        };
        let mut s = String::new();
        emit_header(
            &mut s,
            &cluster_with(vec![struct_dt("SemanticTagStruct")], vec![tag_list]),
        );
    }

    #[test]
    fn non_exhaustive_skipped_for_command_encode_reachable_structs() {
        use std::collections::HashSet;
        let d = Datatype {
            name: "EncStruct".to_string(),
            base: "struct".to_string(),
            kind: "struct".to_string(),
            values: vec![],
            bits: vec![],
            fields: vec![],
            global_name: None,
        };
        // A normal data struct keeps #[non_exhaustive].
        let mut normal = String::new();
        emit_struct(&mut normal, &d, &HashSet::new());
        assert!(normal.contains("#[non_exhaustive]"), "{normal}");
        // A command-encode-reachable struct must stay constructible by callers
        // (they build it to pass to encode_*) -> no #[non_exhaustive].
        let reachable: HashSet<&str> = std::iter::once("EncStruct").collect();
        let mut enc = String::new();
        emit_struct(&mut enc, &d, &reachable);
        assert!(!enc.contains("#[non_exhaustive]"), "{enc}");
    }
    // ---- M9-A3 B4: provisional, choice-group and global-origin rustdoc ----

    fn note_field(
        name: &str,
        provisional: bool,
        choice: Option<(&str, u32, bool, bool)>,
    ) -> FieldDef {
        FieldDef {
            id: 0,
            name: name.to_string(),
            ty: "uint8".to_string(),
            metatype: "integer".to_string(),
            entry_type: None,
            nullable: false,
            optional: true,
            fabric_sensitive: false,
            mandatory_on_write: false,
            provisional,
            choice: choice.map(|(group, count, or_more, or_less)| Choice {
                group: group.to_string(),
                count,
                or_more,
                or_less,
            }),
        }
    }

    #[test]
    fn provisional_ids_and_features_carry_the_provisional_doc() {
        use crate::codegen::model::{Attribute, CommandDef, EventDef, Feature};
        let attr = |name: &str, provisional: bool| Attribute {
            id: u32::from(provisional),
            name: name.to_string(),
            ty: "uint8".to_string(),
            metatype: "integer".to_string(),
            entry_type: None,
            nullable: false,
            optional: true,
            writable: false,
            provisional,
        };
        let mut c = cluster_with(vec![], vec![attr("Plain", false), attr("Draft", true)]);
        c.commands = vec![CommandDef {
            id: 0,
            name: "GoDraft".to_string(),
            direction: "request".to_string(),
            response_id: None,
            fields: vec![],
            provisional: true,
        }];
        c.events = vec![EventDef {
            id: 0,
            name: "Drafted".to_string(),
            priority: "info".to_string(),
            fields: vec![],
            provisional: true,
        }];
        c.features = vec![
            Feature {
                bit: 0,
                code: "PL".to_string(),
                name: "Plain".to_string(),
                provisional: false,
            },
            Feature {
                bit: 1,
                code: "DR".to_string(),
                name: "Draft".to_string(),
                provisional: true,
            },
        ];
        let mut s = String::new();
        emit_ids(&mut s, &c);
        emit_feature_bitflags(&mut s, &c);
        // One line each: the Draft attribute, the command, the event, the DR bit.
        assert_eq!(s.matches(PROVISIONAL_DOC).count(), 4, "{s}");
        assert!(
            s.contains(&format!("/// `Draft`.\n    /// {PROVISIONAL_DOC}\n")),
            "{s}"
        );
        assert!(
            !s.contains(&format!("/// `Plain`.\n    /// {PROVISIONAL_DOC}")),
            "{s}"
        );
    }

    #[test]
    fn choice_groups_are_stated_once_per_group() {
        let fields = vec![
            note_field("ValueUnsigned8", false, Some(("a", 1, false, false))),
            note_field("Other", false, None),
            note_field("CookTime", false, Some(("b", 1, true, false))),
            note_field("ValueSigned8", false, Some(("a", 1, false, false))),
            note_field("CookMode", false, Some(("b", 2, true, false))),
            note_field("OneShot", false, Some(("c", 1, false, true))),
        ];
        assert_eq!(
            choice_docs(&fields),
            [
                "Choice group `a`: a sender includes exactly one of `value_unsigned8`, \
                 `value_signed8`. Not checked when encoding.",
                "Choice group `b`: a sender includes at least one of `cook_time`, `cook_mode`. \
                 Not checked when encoding.",
                "Choice group `c`: a sender includes at most one of `one_shot`. Not checked when \
                 encoding.",
            ]
        );
        assert_eq!(
            choice_docs(&[note_field("Other", false, None)]),
            Vec::<String>::new()
        );
    }

    #[test]
    fn struct_docs_state_global_origin_choice_and_provisional_fields() {
        let d = Datatype {
            name: "LocationDescriptorStruct".to_string(),
            base: "struct".to_string(),
            kind: "struct".to_string(),
            values: vec![],
            bits: vec![],
            fields: vec![
                note_field("A", false, Some(("a", 1, false, false))),
                note_field("B", true, Some(("a", 1, false, false))),
            ],
            global_name: Some("locationdesc".to_string()),
        };
        let mut s = String::new();
        emit_struct(&mut s, &d, &HashSet::new());
        assert!(
            s.starts_with(
                "/// `LocationDescriptorStruct` struct.\n///\n/// Generated from the Matter \
                 global type `locationdesc`.\n///\n/// Choice group `a`: a sender includes \
                 exactly one of `a`, `b`. Not checked when encoding.\n"
            ),
            "{s}"
        );
        assert!(
            s.contains(&format!(
                "/// Field B (tag 0).\n    /// {PROVISIONAL_DOC}\n"
            )),
            "{s}"
        );
        assert_eq!(s.matches(PROVISIONAL_DOC).count(), 1, "{s}");
    }
}
