//! String-building emitter for the uniform cluster module shape (spec §2).
//!
//! Plain `String` building with an indent helper — no template engine (the
//! CHIP codegen's templating is the cautionary tale the spec cites). Output
//! is later normalized by rustfmt, so we optimise for correctness, not
//! whitespace.

use crate::codegen::model::{Cluster, Datatype};
use crate::codegen::rustgen::types::{base_type, ident, rust_type, screaming, snake, Position};
use std::fmt::Write as _;

/// Emit the full Rust module source for one cluster.
#[must_use]
pub fn generate_cluster(c: &Cluster) -> String {
    let mut s = String::new();
    emit_header(&mut s, c);
    emit_ids(&mut s, c);
    emit_feature_bitflags(&mut s, c);
    for d in &c.datatypes {
        emit_datatype(&mut s, d);
    }
    super::emit_codecs::emit_codecs(&mut s, c);
    s
}

/// Emit the shared globals module (`gen/globals.rs`). IDs + generic decoders
/// generated once; per-cluster typed interpretation composes on top.
#[must_use]
pub fn generate_globals() -> String {
    let mut s = String::new();
    s.push_str(
        "//! Global attributes present on every cluster (Matter spec §7.13).\n\
         //! @generated by `cargo xtask codegen` — do not edit.\n\n\
         #![allow(clippy::all, clippy::pedantic, dead_code, unreachable_pub, unused_imports)]\n\n\
         use crate::error::ClusterError;\n\
         use matter_codec::{Element, TlvReader, Value};\n\n\
         /// FeatureMap (0xFFFC).\n\
         pub const FEATURE_MAP: u32 = 0xFFFC;\n\
         /// ClusterRevision (0xFFFD).\n\
         pub const CLUSTER_REVISION: u32 = 0xFFFD;\n\
         /// AttributeList (0xFFFB).\n\
         pub const ATTRIBUTE_LIST: u32 = 0xFFFB;\n\
         /// AcceptedCommandList (0xFFF9).\n\
         pub const ACCEPTED_COMMAND_LIST: u32 = 0xFFF9;\n\
         /// GeneratedCommandList (0xFFF8).\n\
         pub const GENERATED_COMMAND_LIST: u32 = 0xFFF8;\n\n",
    );
    s.push_str(
        "/// Decode a FeatureMap / any `u32` global attribute value.\n\
         ///\n\
         /// # Errors\n\
         /// Returns [`ClusterError`] if the element is not an unsigned int.\n\
         pub fn decode_u32(tlv: &[u8]) -> Result<u32, ClusterError> {\n\
         \x20   let mut r = TlvReader::new(tlv);\n\
         \x20   match r.next()? {\n\
         \x20       Some(Element::Scalar { value: Value::Uint(v), .. }) => {\n\
         \x20           u32::try_from(v).map_err(|_| ClusterError::InvalidLength(\"global u32\"))\n\
         \x20       }\n\
         \x20       _ => Err(ClusterError::UnexpectedType { context: \"global u32\" }),\n\
         \x20   }\n\
         }\n",
    );
    s
}

/// `writeln!` into the buffer (the `Vec`/`String` formatter is infallible).
macro_rules! line {
    ($s:expr, $($arg:tt)*) => {{
        let _ = writeln!($s, $($arg)*);
    }};
}
#[allow(unused_imports)]
pub(crate) use line;

fn emit_header(s: &mut String, c: &Cluster) {
    line!(s, "//! {} cluster (0x{:04X}).", c.name, c.id);
    line!(
        s,
        "//! @generated by `cargo xtask codegen` — do not edit.\n"
    );
    line!(
        s,
        "#![allow(clippy::all, clippy::pedantic, dead_code, unreachable_pub, unused_imports)]\n"
    );
    line!(s, "use crate::datatypes::SemanticTagStruct;");
    line!(s, "use crate::error::ClusterError;");
    line!(s, "use crate::types::Nullable;");
    line!(
        s,
        "use matter_codec::{{ContainerKind, Element, Tag, TlvReader, TlvWriter, Value}};\n"
    );
    line!(s, "/// Cluster ID.");
    line!(s, "pub const CLUSTER_ID: u32 = 0x{:04X};", c.id);
    line!(s, "/// Cluster revision.");
    line!(s, "pub const CLUSTER_REVISION: u16 = {};\n", c.revision);
}

fn emit_ids(s: &mut String, c: &Cluster) {
    line!(s, "/// Command IDs (requests and responses).");
    line!(s, "pub mod command_id {{");
    for cmd in &c.commands {
        line!(s, "    /// `{}` ({}).", cmd.name, cmd.direction);
        line!(
            s,
            "    pub const {}: u32 = 0x{:02X};",
            screaming(&cmd.name),
            cmd.id
        );
    }
    line!(s, "}}\n");

    line!(s, "/// Attribute IDs (cluster-specific).");
    line!(s, "pub mod attribute_id {{");
    for a in &c.attributes {
        line!(s, "    /// `{}`.", a.name);
        line!(
            s,
            "    pub const {}: u32 = 0x{:04X};",
            screaming(&a.name),
            a.id
        );
    }
    line!(s, "}}\n");
}

fn emit_feature_bitflags(s: &mut String, c: &Cluster) {
    if c.features.is_empty() {
        return;
    }
    line!(s, "bitflags::bitflags! {{");
    line!(s, "    /// `{}` feature bits (FeatureMap).", c.name);
    line!(s, "    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]");
    line!(s, "    pub struct Feature: u32 {{");
    for f in &c.features {
        line!(s, "        /// {} ({}).", f.name, f.code);
        line!(s, "        const {} = 1 << {};", screaming(&f.code), f.bit);
    }
    line!(s, "    }}");
    line!(s, "}}\n");
}

fn emit_datatype(s: &mut String, d: &Datatype) {
    match d.kind.as_str() {
        "enum" => emit_enum(s, d),
        "bitmap" => emit_bitmap(s, d),
        "struct" => emit_struct(s, d),
        _ => {} // "scalar": a named alias of a primitive — referenced inline, no decl needed.
    }
}

fn enum_backing(base: &str) -> &'static str {
    if base == "enum16" {
        "u16"
    } else {
        "u8"
    }
}

/// The catch-all "unknown discriminant" variant name for a generated enum.
///
/// Normally `Unknown`, but some Matter enums (`AirQualityEnum`, `PowerModeEnum`,
/// `BatChargeStateEnum`, …) define a member literally named `Unknown`; for those
/// the catch-all becomes `Unrecognized` so the two do not collide. Panics only
/// if a model defines BOTH `Unknown` and `Unrecognized` members (no known Matter
/// enum does) — a loud failure, never a silent miscompile.
fn catch_all_variant(d: &Datatype) -> &'static str {
    let has = |n: &str| d.values.iter().any(|v| v.name == n);
    if !has("Unknown") {
        "Unknown"
    } else if !has("Unrecognized") {
        "Unrecognized"
    } else {
        panic!(
            "enum {} defines both Unknown and Unrecognized members",
            d.name
        )
    }
}

fn emit_enum(s: &mut String, d: &Datatype) {
    let backing = enum_backing(&d.base);
    let catch_all = catch_all_variant(d);
    line!(s, "/// `{}` ({}).", d.name, d.base);
    line!(s, "#[derive(Copy, Clone, Debug, PartialEq, Eq)]");
    line!(s, "pub enum {} {{", d.name);
    for v in &d.values {
        line!(s, "    /// {} = {}.", v.name, v.value);
        line!(s, "    {},", ident(&v.name));
    }
    line!(s, "    /// A value not known to this codegen revision.");
    line!(s, "    {catch_all}({backing}),");
    line!(s, "}}\n");

    line!(s, "impl {} {{", d.name);
    line!(
        s,
        "    /// Decode from its raw discriminant (unknown → `{catch_all}`)."
    );
    line!(s, "    #[must_use]");
    line!(s, "    pub fn from_raw(v: {backing}) -> Self {{");
    line!(s, "        match v {{");
    for v in &d.values {
        line!(s, "            {} => Self::{},", v.value, ident(&v.name));
    }
    line!(s, "            other => Self::{catch_all}(other),");
    line!(s, "        }}");
    line!(s, "    }}");
    line!(s, "    /// The raw discriminant.");
    line!(s, "    #[must_use]");
    line!(s, "    pub fn to_raw(self) -> {backing} {{");
    line!(s, "        match self {{");
    for v in &d.values {
        line!(s, "            Self::{} => {},", ident(&v.name), v.value);
    }
    line!(s, "            Self::{catch_all}(v) => v,");
    line!(s, "        }}");
    line!(s, "    }}");
    line!(s, "}}\n");
}

fn emit_bitmap(s: &mut String, d: &Datatype) {
    let backing = match d.base.as_str() {
        "map16" => "u16",
        "map32" => "u32",
        _ => "u8",
    };
    line!(s, "bitflags::bitflags! {{");
    line!(s, "    /// `{}` ({}).", d.name, d.base);
    line!(s, "    #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]");
    line!(s, "    pub struct {}: {} {{", d.name, backing);
    for b in &d.bits {
        if let Some(bit) = b.bit {
            line!(s, "        /// {}.", b.name);
            line!(s, "        const {} = 1 << {};", screaming(&b.name), bit);
        }
    }
    line!(s, "    }}");
    line!(s, "}}\n");
}

fn emit_struct(s: &mut String, d: &Datatype) {
    line!(s, "/// `{}` struct.", d.name);
    line!(s, "#[derive(Clone, Debug, PartialEq)]");
    line!(s, "#[non_exhaustive]");
    line!(s, "pub struct {} {{", d.name);
    for f in &d.fields {
        let ty = rust_type(
            &f.ty,
            f.entry_type.as_deref(),
            f.nullable,
            f.optional,
            Position::Field,
        );
        line!(s, "    /// Field {} (tag {}).", f.name, f.id);
        line!(s, "    pub {}: {},", snake(&f.name), ty);
    }
    line!(s, "}}\n");
    // The struct's encode/decode impls are emitted by the codec pass (next
    // task), since they share the scalar read/write helpers.
    let _ = (base_type, ident); // keep imports used regardless of branch
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::model::{Datatype, EnumValue};

    fn enum_dt(name: &str, base: &str, values: &[(u32, &str)]) -> Datatype {
        Datatype {
            name: name.to_string(),
            base: base.to_string(),
            kind: "enum".to_string(),
            values: values
                .iter()
                .map(|(v, n)| EnumValue {
                    value: *v,
                    name: (*n).to_string(),
                })
                .collect(),
            bits: vec![],
            fields: vec![],
        }
    }

    #[test]
    fn enum_without_unknown_member_keeps_unknown_catch_all() {
        let mut s = String::new();
        emit_enum(
            &mut s,
            &enum_dt("StartUpOnOffEnum", "enum8", &[(0, "Off"), (1, "On")]),
        );
        assert!(
            s.contains("Unknown(u8),"),
            "expected Unknown catch-all:\n{s}"
        );
        assert!(s.contains("other => Self::Unknown(other),"), "{s}");
        assert!(s.contains("Self::Unknown(v) => v,"), "{s}");
    }

    #[test]
    fn enum_with_unknown_member_uses_unrecognized_catch_all() {
        let mut s = String::new();
        emit_enum(
            &mut s,
            &enum_dt("AirQualityEnum", "enum8", &[(0, "Unknown"), (1, "Good")]),
        );
        // The model member stays `Unknown` (a fieldless variant); the catch-all
        // is renamed to `Unrecognized` to avoid a duplicate-variant collision.
        assert!(
            s.contains("    Unknown,\n"),
            "model member Unknown missing:\n{s}"
        );
        assert!(
            s.contains("Unrecognized(u8),"),
            "catch-all not renamed:\n{s}"
        );
        assert!(
            !s.contains("Unknown(u8)"),
            "colliding catch-all present:\n{s}"
        );
        assert!(s.contains("other => Self::Unrecognized(other),"), "{s}");
        assert!(s.contains("Self::Unrecognized(v) => v,"), "{s}");
    }
}
